-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2020.1
-- Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity top is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    src_V_0_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    src_V_0_empty_n : IN STD_LOGIC;
    src_V_0_read : OUT STD_LOGIC;
    src_V_1_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    src_V_1_empty_n : IN STD_LOGIC;
    src_V_1_read : OUT STD_LOGIC;
    src_V_2_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    src_V_2_empty_n : IN STD_LOGIC;
    src_V_2_read : OUT STD_LOGIC;
    src_V_3_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    src_V_3_empty_n : IN STD_LOGIC;
    src_V_3_read : OUT STD_LOGIC;
    src_V_4_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    src_V_4_empty_n : IN STD_LOGIC;
    src_V_4_read : OUT STD_LOGIC;
    src_V_5_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    src_V_5_empty_n : IN STD_LOGIC;
    src_V_5_read : OUT STD_LOGIC;
    src_V_6_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    src_V_6_empty_n : IN STD_LOGIC;
    src_V_6_read : OUT STD_LOGIC;
    src_V_7_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    src_V_7_empty_n : IN STD_LOGIC;
    src_V_7_read : OUT STD_LOGIC;
    src_V_8_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    src_V_8_empty_n : IN STD_LOGIC;
    src_V_8_read : OUT STD_LOGIC;
    src_V_9_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    src_V_9_empty_n : IN STD_LOGIC;
    src_V_9_read : OUT STD_LOGIC;
    dst_V_0_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    dst_V_0_full_n : IN STD_LOGIC;
    dst_V_0_write : OUT STD_LOGIC;
    dst_V_1_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    dst_V_1_full_n : IN STD_LOGIC;
    dst_V_1_write : OUT STD_LOGIC;
    dst_V_2_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    dst_V_2_full_n : IN STD_LOGIC;
    dst_V_2_write : OUT STD_LOGIC;
    dst_V_3_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    dst_V_3_full_n : IN STD_LOGIC;
    dst_V_3_write : OUT STD_LOGIC;
    dst_V_4_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    dst_V_4_full_n : IN STD_LOGIC;
    dst_V_4_write : OUT STD_LOGIC );
end;


architecture behav of top is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "top_top,hls_ip_2020_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu7ev-ffvc1156-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.969000,HLS_SYN_LAT=225,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=1327,HLS_SYN_LUT=1626,HLS_VERSION=2020_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv5_F : STD_LOGIC_VECTOR (4 downto 0) := "01111";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal trunc_ln47_fu_228_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln47_reg_251 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal i_fu_238_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal i_reg_258 : STD_LOGIC_VECTOR (4 downto 0);
    signal icmp_ln878_fu_244_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln878_reg_263 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln47_fu_232_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_221_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln878_1_reg_268 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln878_2_reg_273 : STD_LOGIC_VECTOR (0 downto 0);
    signal ping_0_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal ping_0_ce0 : STD_LOGIC;
    signal ping_0_we0 : STD_LOGIC;
    signal ping_0_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal ping_1_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal ping_1_ce0 : STD_LOGIC;
    signal ping_1_we0 : STD_LOGIC;
    signal ping_1_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal ping_2_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal ping_2_ce0 : STD_LOGIC;
    signal ping_2_we0 : STD_LOGIC;
    signal ping_2_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal ping_3_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal ping_3_ce0 : STD_LOGIC;
    signal ping_3_we0 : STD_LOGIC;
    signal ping_3_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal ping_4_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal ping_4_ce0 : STD_LOGIC;
    signal ping_4_we0 : STD_LOGIC;
    signal ping_4_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal ping_5_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal ping_5_ce0 : STD_LOGIC;
    signal ping_5_we0 : STD_LOGIC;
    signal ping_5_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal ping_6_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal ping_6_ce0 : STD_LOGIC;
    signal ping_6_we0 : STD_LOGIC;
    signal ping_6_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal ping_7_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal ping_7_ce0 : STD_LOGIC;
    signal ping_7_we0 : STD_LOGIC;
    signal ping_7_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal ping_8_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal ping_8_ce0 : STD_LOGIC;
    signal ping_8_we0 : STD_LOGIC;
    signal ping_8_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal ping_9_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal ping_9_ce0 : STD_LOGIC;
    signal ping_9_we0 : STD_LOGIC;
    signal ping_9_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal pong_0_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal pong_0_ce0 : STD_LOGIC;
    signal pong_0_we0 : STD_LOGIC;
    signal pong_0_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal pong_1_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal pong_1_ce0 : STD_LOGIC;
    signal pong_1_we0 : STD_LOGIC;
    signal pong_1_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal pong_2_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal pong_2_ce0 : STD_LOGIC;
    signal pong_2_we0 : STD_LOGIC;
    signal pong_2_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal pong_3_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal pong_3_ce0 : STD_LOGIC;
    signal pong_3_we0 : STD_LOGIC;
    signal pong_3_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal pong_4_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal pong_4_ce0 : STD_LOGIC;
    signal pong_4_we0 : STD_LOGIC;
    signal pong_4_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal pong_5_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal pong_5_ce0 : STD_LOGIC;
    signal pong_5_we0 : STD_LOGIC;
    signal pong_5_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal pong_6_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal pong_6_ce0 : STD_LOGIC;
    signal pong_6_we0 : STD_LOGIC;
    signal pong_6_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal pong_7_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal pong_7_ce0 : STD_LOGIC;
    signal pong_7_we0 : STD_LOGIC;
    signal pong_7_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal pong_8_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal pong_8_ce0 : STD_LOGIC;
    signal pong_8_we0 : STD_LOGIC;
    signal pong_8_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal pong_9_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal pong_9_ce0 : STD_LOGIC;
    signal pong_9_we0 : STD_LOGIC;
    signal pong_9_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_buf2stream_fu_161_ap_start : STD_LOGIC;
    signal grp_buf2stream_fu_161_ap_done : STD_LOGIC;
    signal grp_buf2stream_fu_161_ap_idle : STD_LOGIC;
    signal grp_buf2stream_fu_161_ap_ready : STD_LOGIC;
    signal grp_buf2stream_fu_161_buffer_0_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_buf2stream_fu_161_buffer_0_ce0 : STD_LOGIC;
    signal grp_buf2stream_fu_161_buffer_0_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_buf2stream_fu_161_buffer_1_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_buf2stream_fu_161_buffer_1_ce0 : STD_LOGIC;
    signal grp_buf2stream_fu_161_buffer_1_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_buf2stream_fu_161_buffer_2_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_buf2stream_fu_161_buffer_2_ce0 : STD_LOGIC;
    signal grp_buf2stream_fu_161_buffer_2_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_buf2stream_fu_161_buffer_3_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_buf2stream_fu_161_buffer_3_ce0 : STD_LOGIC;
    signal grp_buf2stream_fu_161_buffer_3_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_buf2stream_fu_161_buffer_4_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_buf2stream_fu_161_buffer_4_ce0 : STD_LOGIC;
    signal grp_buf2stream_fu_161_buffer_4_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_buf2stream_fu_161_buffer_5_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_buf2stream_fu_161_buffer_5_ce0 : STD_LOGIC;
    signal grp_buf2stream_fu_161_buffer_5_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_buf2stream_fu_161_buffer_6_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_buf2stream_fu_161_buffer_6_ce0 : STD_LOGIC;
    signal grp_buf2stream_fu_161_buffer_6_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_buf2stream_fu_161_buffer_7_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_buf2stream_fu_161_buffer_7_ce0 : STD_LOGIC;
    signal grp_buf2stream_fu_161_buffer_7_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_buf2stream_fu_161_buffer_8_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_buf2stream_fu_161_buffer_8_ce0 : STD_LOGIC;
    signal grp_buf2stream_fu_161_buffer_8_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_buf2stream_fu_161_buffer_9_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_buf2stream_fu_161_buffer_9_ce0 : STD_LOGIC;
    signal grp_buf2stream_fu_161_buffer_9_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_buf2stream_fu_161_dst_V_din : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_buf2stream_fu_161_dst_V_write : STD_LOGIC;
    signal grp_buf2stream_fu_161_dst_1_V_din : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_buf2stream_fu_161_dst_1_V_write : STD_LOGIC;
    signal grp_buf2stream_fu_161_dst_2_V_din : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_buf2stream_fu_161_dst_2_V_write : STD_LOGIC;
    signal grp_buf2stream_fu_161_dst_3_V_din : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_buf2stream_fu_161_dst_3_V_write : STD_LOGIC;
    signal grp_buf2stream_fu_161_dst_4_V_din : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_buf2stream_fu_161_dst_4_V_write : STD_LOGIC;
    signal grp_buf2stream_fu_161_enable : STD_LOGIC;
    signal grp_stream2buf_fu_186_ap_start : STD_LOGIC;
    signal grp_stream2buf_fu_186_ap_done : STD_LOGIC;
    signal grp_stream2buf_fu_186_ap_idle : STD_LOGIC;
    signal grp_stream2buf_fu_186_ap_ready : STD_LOGIC;
    signal grp_stream2buf_fu_186_src_V_read : STD_LOGIC;
    signal grp_stream2buf_fu_186_src_1_V_read : STD_LOGIC;
    signal grp_stream2buf_fu_186_src_2_V_read : STD_LOGIC;
    signal grp_stream2buf_fu_186_src_3_V_read : STD_LOGIC;
    signal grp_stream2buf_fu_186_src_4_V_read : STD_LOGIC;
    signal grp_stream2buf_fu_186_src_5_V_read : STD_LOGIC;
    signal grp_stream2buf_fu_186_src_6_V_read : STD_LOGIC;
    signal grp_stream2buf_fu_186_src_7_V_read : STD_LOGIC;
    signal grp_stream2buf_fu_186_src_8_V_read : STD_LOGIC;
    signal grp_stream2buf_fu_186_src_9_V_read : STD_LOGIC;
    signal grp_stream2buf_fu_186_buffer_0_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_stream2buf_fu_186_buffer_0_ce0 : STD_LOGIC;
    signal grp_stream2buf_fu_186_buffer_0_we0 : STD_LOGIC;
    signal grp_stream2buf_fu_186_buffer_0_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_stream2buf_fu_186_buffer_1_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_stream2buf_fu_186_buffer_1_ce0 : STD_LOGIC;
    signal grp_stream2buf_fu_186_buffer_1_we0 : STD_LOGIC;
    signal grp_stream2buf_fu_186_buffer_1_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_stream2buf_fu_186_buffer_2_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_stream2buf_fu_186_buffer_2_ce0 : STD_LOGIC;
    signal grp_stream2buf_fu_186_buffer_2_we0 : STD_LOGIC;
    signal grp_stream2buf_fu_186_buffer_2_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_stream2buf_fu_186_buffer_3_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_stream2buf_fu_186_buffer_3_ce0 : STD_LOGIC;
    signal grp_stream2buf_fu_186_buffer_3_we0 : STD_LOGIC;
    signal grp_stream2buf_fu_186_buffer_3_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_stream2buf_fu_186_buffer_4_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_stream2buf_fu_186_buffer_4_ce0 : STD_LOGIC;
    signal grp_stream2buf_fu_186_buffer_4_we0 : STD_LOGIC;
    signal grp_stream2buf_fu_186_buffer_4_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_stream2buf_fu_186_buffer_5_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_stream2buf_fu_186_buffer_5_ce0 : STD_LOGIC;
    signal grp_stream2buf_fu_186_buffer_5_we0 : STD_LOGIC;
    signal grp_stream2buf_fu_186_buffer_5_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_stream2buf_fu_186_buffer_6_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_stream2buf_fu_186_buffer_6_ce0 : STD_LOGIC;
    signal grp_stream2buf_fu_186_buffer_6_we0 : STD_LOGIC;
    signal grp_stream2buf_fu_186_buffer_6_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_stream2buf_fu_186_buffer_7_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_stream2buf_fu_186_buffer_7_ce0 : STD_LOGIC;
    signal grp_stream2buf_fu_186_buffer_7_we0 : STD_LOGIC;
    signal grp_stream2buf_fu_186_buffer_7_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_stream2buf_fu_186_buffer_8_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_stream2buf_fu_186_buffer_8_ce0 : STD_LOGIC;
    signal grp_stream2buf_fu_186_buffer_8_we0 : STD_LOGIC;
    signal grp_stream2buf_fu_186_buffer_8_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_stream2buf_fu_186_buffer_9_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_stream2buf_fu_186_buffer_9_ce0 : STD_LOGIC;
    signal grp_stream2buf_fu_186_buffer_9_we0 : STD_LOGIC;
    signal grp_stream2buf_fu_186_buffer_9_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_stream2buf_fu_186_enable : STD_LOGIC;
    signal p_Val2_s_reg_150 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_block_state3_on_subcall_done : BOOLEAN;
    signal grp_buf2stream_fu_161_ap_start_reg : STD_LOGIC := '0';
    signal grp_stream2buf_fu_186_ap_start_reg : STD_LOGIC := '0';
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);

    component top_buf2stream IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        buffer_0_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        buffer_0_ce0 : OUT STD_LOGIC;
        buffer_0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        buffer_1_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        buffer_1_ce0 : OUT STD_LOGIC;
        buffer_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        buffer_2_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        buffer_2_ce0 : OUT STD_LOGIC;
        buffer_2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        buffer_3_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        buffer_3_ce0 : OUT STD_LOGIC;
        buffer_3_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        buffer_4_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        buffer_4_ce0 : OUT STD_LOGIC;
        buffer_4_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        buffer_5_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        buffer_5_ce0 : OUT STD_LOGIC;
        buffer_5_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        buffer_6_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        buffer_6_ce0 : OUT STD_LOGIC;
        buffer_6_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        buffer_7_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        buffer_7_ce0 : OUT STD_LOGIC;
        buffer_7_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        buffer_8_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        buffer_8_ce0 : OUT STD_LOGIC;
        buffer_8_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        buffer_9_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        buffer_9_ce0 : OUT STD_LOGIC;
        buffer_9_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        dst_V_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        dst_V_full_n : IN STD_LOGIC;
        dst_V_write : OUT STD_LOGIC;
        dst_1_V_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        dst_1_V_full_n : IN STD_LOGIC;
        dst_1_V_write : OUT STD_LOGIC;
        dst_2_V_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        dst_2_V_full_n : IN STD_LOGIC;
        dst_2_V_write : OUT STD_LOGIC;
        dst_3_V_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        dst_3_V_full_n : IN STD_LOGIC;
        dst_3_V_write : OUT STD_LOGIC;
        dst_4_V_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        dst_4_V_full_n : IN STD_LOGIC;
        dst_4_V_write : OUT STD_LOGIC;
        enable : IN STD_LOGIC );
    end component;


    component top_stream2buf IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        src_V_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        src_V_empty_n : IN STD_LOGIC;
        src_V_read : OUT STD_LOGIC;
        src_1_V_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        src_1_V_empty_n : IN STD_LOGIC;
        src_1_V_read : OUT STD_LOGIC;
        src_2_V_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        src_2_V_empty_n : IN STD_LOGIC;
        src_2_V_read : OUT STD_LOGIC;
        src_3_V_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        src_3_V_empty_n : IN STD_LOGIC;
        src_3_V_read : OUT STD_LOGIC;
        src_4_V_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        src_4_V_empty_n : IN STD_LOGIC;
        src_4_V_read : OUT STD_LOGIC;
        src_5_V_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        src_5_V_empty_n : IN STD_LOGIC;
        src_5_V_read : OUT STD_LOGIC;
        src_6_V_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        src_6_V_empty_n : IN STD_LOGIC;
        src_6_V_read : OUT STD_LOGIC;
        src_7_V_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        src_7_V_empty_n : IN STD_LOGIC;
        src_7_V_read : OUT STD_LOGIC;
        src_8_V_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        src_8_V_empty_n : IN STD_LOGIC;
        src_8_V_read : OUT STD_LOGIC;
        src_9_V_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        src_9_V_empty_n : IN STD_LOGIC;
        src_9_V_read : OUT STD_LOGIC;
        buffer_0_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        buffer_0_ce0 : OUT STD_LOGIC;
        buffer_0_we0 : OUT STD_LOGIC;
        buffer_0_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        buffer_1_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        buffer_1_ce0 : OUT STD_LOGIC;
        buffer_1_we0 : OUT STD_LOGIC;
        buffer_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        buffer_2_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        buffer_2_ce0 : OUT STD_LOGIC;
        buffer_2_we0 : OUT STD_LOGIC;
        buffer_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        buffer_3_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        buffer_3_ce0 : OUT STD_LOGIC;
        buffer_3_we0 : OUT STD_LOGIC;
        buffer_3_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        buffer_4_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        buffer_4_ce0 : OUT STD_LOGIC;
        buffer_4_we0 : OUT STD_LOGIC;
        buffer_4_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        buffer_5_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        buffer_5_ce0 : OUT STD_LOGIC;
        buffer_5_we0 : OUT STD_LOGIC;
        buffer_5_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        buffer_6_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        buffer_6_ce0 : OUT STD_LOGIC;
        buffer_6_we0 : OUT STD_LOGIC;
        buffer_6_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        buffer_7_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        buffer_7_ce0 : OUT STD_LOGIC;
        buffer_7_we0 : OUT STD_LOGIC;
        buffer_7_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        buffer_8_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        buffer_8_ce0 : OUT STD_LOGIC;
        buffer_8_we0 : OUT STD_LOGIC;
        buffer_8_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        buffer_9_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        buffer_9_ce0 : OUT STD_LOGIC;
        buffer_9_we0 : OUT STD_LOGIC;
        buffer_9_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        enable : IN STD_LOGIC );
    end component;


    component top_ping_0 IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    ping_0_U : component top_ping_0
    generic map (
        DataWidth => 32,
        AddressRange => 10,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ping_0_address0,
        ce0 => ping_0_ce0,
        we0 => ping_0_we0,
        d0 => grp_stream2buf_fu_186_buffer_0_d0,
        q0 => ping_0_q0);

    ping_1_U : component top_ping_0
    generic map (
        DataWidth => 32,
        AddressRange => 10,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ping_1_address0,
        ce0 => ping_1_ce0,
        we0 => ping_1_we0,
        d0 => grp_stream2buf_fu_186_buffer_1_d0,
        q0 => ping_1_q0);

    ping_2_U : component top_ping_0
    generic map (
        DataWidth => 32,
        AddressRange => 10,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ping_2_address0,
        ce0 => ping_2_ce0,
        we0 => ping_2_we0,
        d0 => grp_stream2buf_fu_186_buffer_2_d0,
        q0 => ping_2_q0);

    ping_3_U : component top_ping_0
    generic map (
        DataWidth => 32,
        AddressRange => 10,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ping_3_address0,
        ce0 => ping_3_ce0,
        we0 => ping_3_we0,
        d0 => grp_stream2buf_fu_186_buffer_3_d0,
        q0 => ping_3_q0);

    ping_4_U : component top_ping_0
    generic map (
        DataWidth => 32,
        AddressRange => 10,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ping_4_address0,
        ce0 => ping_4_ce0,
        we0 => ping_4_we0,
        d0 => grp_stream2buf_fu_186_buffer_4_d0,
        q0 => ping_4_q0);

    ping_5_U : component top_ping_0
    generic map (
        DataWidth => 32,
        AddressRange => 10,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ping_5_address0,
        ce0 => ping_5_ce0,
        we0 => ping_5_we0,
        d0 => grp_stream2buf_fu_186_buffer_5_d0,
        q0 => ping_5_q0);

    ping_6_U : component top_ping_0
    generic map (
        DataWidth => 32,
        AddressRange => 10,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ping_6_address0,
        ce0 => ping_6_ce0,
        we0 => ping_6_we0,
        d0 => grp_stream2buf_fu_186_buffer_6_d0,
        q0 => ping_6_q0);

    ping_7_U : component top_ping_0
    generic map (
        DataWidth => 32,
        AddressRange => 10,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ping_7_address0,
        ce0 => ping_7_ce0,
        we0 => ping_7_we0,
        d0 => grp_stream2buf_fu_186_buffer_7_d0,
        q0 => ping_7_q0);

    ping_8_U : component top_ping_0
    generic map (
        DataWidth => 32,
        AddressRange => 10,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ping_8_address0,
        ce0 => ping_8_ce0,
        we0 => ping_8_we0,
        d0 => grp_stream2buf_fu_186_buffer_8_d0,
        q0 => ping_8_q0);

    ping_9_U : component top_ping_0
    generic map (
        DataWidth => 32,
        AddressRange => 10,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ping_9_address0,
        ce0 => ping_9_ce0,
        we0 => ping_9_we0,
        d0 => grp_stream2buf_fu_186_buffer_9_d0,
        q0 => ping_9_q0);

    pong_0_U : component top_ping_0
    generic map (
        DataWidth => 32,
        AddressRange => 10,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => pong_0_address0,
        ce0 => pong_0_ce0,
        we0 => pong_0_we0,
        d0 => grp_stream2buf_fu_186_buffer_0_d0,
        q0 => pong_0_q0);

    pong_1_U : component top_ping_0
    generic map (
        DataWidth => 32,
        AddressRange => 10,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => pong_1_address0,
        ce0 => pong_1_ce0,
        we0 => pong_1_we0,
        d0 => grp_stream2buf_fu_186_buffer_1_d0,
        q0 => pong_1_q0);

    pong_2_U : component top_ping_0
    generic map (
        DataWidth => 32,
        AddressRange => 10,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => pong_2_address0,
        ce0 => pong_2_ce0,
        we0 => pong_2_we0,
        d0 => grp_stream2buf_fu_186_buffer_2_d0,
        q0 => pong_2_q0);

    pong_3_U : component top_ping_0
    generic map (
        DataWidth => 32,
        AddressRange => 10,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => pong_3_address0,
        ce0 => pong_3_ce0,
        we0 => pong_3_we0,
        d0 => grp_stream2buf_fu_186_buffer_3_d0,
        q0 => pong_3_q0);

    pong_4_U : component top_ping_0
    generic map (
        DataWidth => 32,
        AddressRange => 10,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => pong_4_address0,
        ce0 => pong_4_ce0,
        we0 => pong_4_we0,
        d0 => grp_stream2buf_fu_186_buffer_4_d0,
        q0 => pong_4_q0);

    pong_5_U : component top_ping_0
    generic map (
        DataWidth => 32,
        AddressRange => 10,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => pong_5_address0,
        ce0 => pong_5_ce0,
        we0 => pong_5_we0,
        d0 => grp_stream2buf_fu_186_buffer_5_d0,
        q0 => pong_5_q0);

    pong_6_U : component top_ping_0
    generic map (
        DataWidth => 32,
        AddressRange => 10,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => pong_6_address0,
        ce0 => pong_6_ce0,
        we0 => pong_6_we0,
        d0 => grp_stream2buf_fu_186_buffer_6_d0,
        q0 => pong_6_q0);

    pong_7_U : component top_ping_0
    generic map (
        DataWidth => 32,
        AddressRange => 10,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => pong_7_address0,
        ce0 => pong_7_ce0,
        we0 => pong_7_we0,
        d0 => grp_stream2buf_fu_186_buffer_7_d0,
        q0 => pong_7_q0);

    pong_8_U : component top_ping_0
    generic map (
        DataWidth => 32,
        AddressRange => 10,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => pong_8_address0,
        ce0 => pong_8_ce0,
        we0 => pong_8_we0,
        d0 => grp_stream2buf_fu_186_buffer_8_d0,
        q0 => pong_8_q0);

    pong_9_U : component top_ping_0
    generic map (
        DataWidth => 32,
        AddressRange => 10,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => pong_9_address0,
        ce0 => pong_9_ce0,
        we0 => pong_9_we0,
        d0 => grp_stream2buf_fu_186_buffer_9_d0,
        q0 => pong_9_q0);

    grp_buf2stream_fu_161 : component top_buf2stream
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_buf2stream_fu_161_ap_start,
        ap_done => grp_buf2stream_fu_161_ap_done,
        ap_idle => grp_buf2stream_fu_161_ap_idle,
        ap_ready => grp_buf2stream_fu_161_ap_ready,
        buffer_0_address0 => grp_buf2stream_fu_161_buffer_0_address0,
        buffer_0_ce0 => grp_buf2stream_fu_161_buffer_0_ce0,
        buffer_0_q0 => grp_buf2stream_fu_161_buffer_0_q0,
        buffer_1_address0 => grp_buf2stream_fu_161_buffer_1_address0,
        buffer_1_ce0 => grp_buf2stream_fu_161_buffer_1_ce0,
        buffer_1_q0 => grp_buf2stream_fu_161_buffer_1_q0,
        buffer_2_address0 => grp_buf2stream_fu_161_buffer_2_address0,
        buffer_2_ce0 => grp_buf2stream_fu_161_buffer_2_ce0,
        buffer_2_q0 => grp_buf2stream_fu_161_buffer_2_q0,
        buffer_3_address0 => grp_buf2stream_fu_161_buffer_3_address0,
        buffer_3_ce0 => grp_buf2stream_fu_161_buffer_3_ce0,
        buffer_3_q0 => grp_buf2stream_fu_161_buffer_3_q0,
        buffer_4_address0 => grp_buf2stream_fu_161_buffer_4_address0,
        buffer_4_ce0 => grp_buf2stream_fu_161_buffer_4_ce0,
        buffer_4_q0 => grp_buf2stream_fu_161_buffer_4_q0,
        buffer_5_address0 => grp_buf2stream_fu_161_buffer_5_address0,
        buffer_5_ce0 => grp_buf2stream_fu_161_buffer_5_ce0,
        buffer_5_q0 => grp_buf2stream_fu_161_buffer_5_q0,
        buffer_6_address0 => grp_buf2stream_fu_161_buffer_6_address0,
        buffer_6_ce0 => grp_buf2stream_fu_161_buffer_6_ce0,
        buffer_6_q0 => grp_buf2stream_fu_161_buffer_6_q0,
        buffer_7_address0 => grp_buf2stream_fu_161_buffer_7_address0,
        buffer_7_ce0 => grp_buf2stream_fu_161_buffer_7_ce0,
        buffer_7_q0 => grp_buf2stream_fu_161_buffer_7_q0,
        buffer_8_address0 => grp_buf2stream_fu_161_buffer_8_address0,
        buffer_8_ce0 => grp_buf2stream_fu_161_buffer_8_ce0,
        buffer_8_q0 => grp_buf2stream_fu_161_buffer_8_q0,
        buffer_9_address0 => grp_buf2stream_fu_161_buffer_9_address0,
        buffer_9_ce0 => grp_buf2stream_fu_161_buffer_9_ce0,
        buffer_9_q0 => grp_buf2stream_fu_161_buffer_9_q0,
        dst_V_din => grp_buf2stream_fu_161_dst_V_din,
        dst_V_full_n => dst_V_0_full_n,
        dst_V_write => grp_buf2stream_fu_161_dst_V_write,
        dst_1_V_din => grp_buf2stream_fu_161_dst_1_V_din,
        dst_1_V_full_n => dst_V_1_full_n,
        dst_1_V_write => grp_buf2stream_fu_161_dst_1_V_write,
        dst_2_V_din => grp_buf2stream_fu_161_dst_2_V_din,
        dst_2_V_full_n => dst_V_2_full_n,
        dst_2_V_write => grp_buf2stream_fu_161_dst_2_V_write,
        dst_3_V_din => grp_buf2stream_fu_161_dst_3_V_din,
        dst_3_V_full_n => dst_V_3_full_n,
        dst_3_V_write => grp_buf2stream_fu_161_dst_3_V_write,
        dst_4_V_din => grp_buf2stream_fu_161_dst_4_V_din,
        dst_4_V_full_n => dst_V_4_full_n,
        dst_4_V_write => grp_buf2stream_fu_161_dst_4_V_write,
        enable => grp_buf2stream_fu_161_enable);

    grp_stream2buf_fu_186 : component top_stream2buf
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_stream2buf_fu_186_ap_start,
        ap_done => grp_stream2buf_fu_186_ap_done,
        ap_idle => grp_stream2buf_fu_186_ap_idle,
        ap_ready => grp_stream2buf_fu_186_ap_ready,
        src_V_dout => src_V_0_dout,
        src_V_empty_n => src_V_0_empty_n,
        src_V_read => grp_stream2buf_fu_186_src_V_read,
        src_1_V_dout => src_V_1_dout,
        src_1_V_empty_n => src_V_1_empty_n,
        src_1_V_read => grp_stream2buf_fu_186_src_1_V_read,
        src_2_V_dout => src_V_2_dout,
        src_2_V_empty_n => src_V_2_empty_n,
        src_2_V_read => grp_stream2buf_fu_186_src_2_V_read,
        src_3_V_dout => src_V_3_dout,
        src_3_V_empty_n => src_V_3_empty_n,
        src_3_V_read => grp_stream2buf_fu_186_src_3_V_read,
        src_4_V_dout => src_V_4_dout,
        src_4_V_empty_n => src_V_4_empty_n,
        src_4_V_read => grp_stream2buf_fu_186_src_4_V_read,
        src_5_V_dout => src_V_5_dout,
        src_5_V_empty_n => src_V_5_empty_n,
        src_5_V_read => grp_stream2buf_fu_186_src_5_V_read,
        src_6_V_dout => src_V_6_dout,
        src_6_V_empty_n => src_V_6_empty_n,
        src_6_V_read => grp_stream2buf_fu_186_src_6_V_read,
        src_7_V_dout => src_V_7_dout,
        src_7_V_empty_n => src_V_7_empty_n,
        src_7_V_read => grp_stream2buf_fu_186_src_7_V_read,
        src_8_V_dout => src_V_8_dout,
        src_8_V_empty_n => src_V_8_empty_n,
        src_8_V_read => grp_stream2buf_fu_186_src_8_V_read,
        src_9_V_dout => src_V_9_dout,
        src_9_V_empty_n => src_V_9_empty_n,
        src_9_V_read => grp_stream2buf_fu_186_src_9_V_read,
        buffer_0_address0 => grp_stream2buf_fu_186_buffer_0_address0,
        buffer_0_ce0 => grp_stream2buf_fu_186_buffer_0_ce0,
        buffer_0_we0 => grp_stream2buf_fu_186_buffer_0_we0,
        buffer_0_d0 => grp_stream2buf_fu_186_buffer_0_d0,
        buffer_1_address0 => grp_stream2buf_fu_186_buffer_1_address0,
        buffer_1_ce0 => grp_stream2buf_fu_186_buffer_1_ce0,
        buffer_1_we0 => grp_stream2buf_fu_186_buffer_1_we0,
        buffer_1_d0 => grp_stream2buf_fu_186_buffer_1_d0,
        buffer_2_address0 => grp_stream2buf_fu_186_buffer_2_address0,
        buffer_2_ce0 => grp_stream2buf_fu_186_buffer_2_ce0,
        buffer_2_we0 => grp_stream2buf_fu_186_buffer_2_we0,
        buffer_2_d0 => grp_stream2buf_fu_186_buffer_2_d0,
        buffer_3_address0 => grp_stream2buf_fu_186_buffer_3_address0,
        buffer_3_ce0 => grp_stream2buf_fu_186_buffer_3_ce0,
        buffer_3_we0 => grp_stream2buf_fu_186_buffer_3_we0,
        buffer_3_d0 => grp_stream2buf_fu_186_buffer_3_d0,
        buffer_4_address0 => grp_stream2buf_fu_186_buffer_4_address0,
        buffer_4_ce0 => grp_stream2buf_fu_186_buffer_4_ce0,
        buffer_4_we0 => grp_stream2buf_fu_186_buffer_4_we0,
        buffer_4_d0 => grp_stream2buf_fu_186_buffer_4_d0,
        buffer_5_address0 => grp_stream2buf_fu_186_buffer_5_address0,
        buffer_5_ce0 => grp_stream2buf_fu_186_buffer_5_ce0,
        buffer_5_we0 => grp_stream2buf_fu_186_buffer_5_we0,
        buffer_5_d0 => grp_stream2buf_fu_186_buffer_5_d0,
        buffer_6_address0 => grp_stream2buf_fu_186_buffer_6_address0,
        buffer_6_ce0 => grp_stream2buf_fu_186_buffer_6_ce0,
        buffer_6_we0 => grp_stream2buf_fu_186_buffer_6_we0,
        buffer_6_d0 => grp_stream2buf_fu_186_buffer_6_d0,
        buffer_7_address0 => grp_stream2buf_fu_186_buffer_7_address0,
        buffer_7_ce0 => grp_stream2buf_fu_186_buffer_7_ce0,
        buffer_7_we0 => grp_stream2buf_fu_186_buffer_7_we0,
        buffer_7_d0 => grp_stream2buf_fu_186_buffer_7_d0,
        buffer_8_address0 => grp_stream2buf_fu_186_buffer_8_address0,
        buffer_8_ce0 => grp_stream2buf_fu_186_buffer_8_ce0,
        buffer_8_we0 => grp_stream2buf_fu_186_buffer_8_we0,
        buffer_8_d0 => grp_stream2buf_fu_186_buffer_8_d0,
        buffer_9_address0 => grp_stream2buf_fu_186_buffer_9_address0,
        buffer_9_ce0 => grp_stream2buf_fu_186_buffer_9_ce0,
        buffer_9_we0 => grp_stream2buf_fu_186_buffer_9_we0,
        buffer_9_d0 => grp_stream2buf_fu_186_buffer_9_d0,
        enable => grp_stream2buf_fu_186_enable);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_buf2stream_fu_161_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_buf2stream_fu_161_ap_start_reg <= ap_const_logic_0;
            else
                if ((((icmp_ln47_fu_232_p2 = ap_const_lv1_0) and (trunc_ln47_fu_228_p1 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2)) or ((icmp_ln47_fu_232_p2 = ap_const_lv1_0) and (trunc_ln47_fu_228_p1 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
                    grp_buf2stream_fu_161_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_buf2stream_fu_161_ap_ready = ap_const_logic_1)) then 
                    grp_buf2stream_fu_161_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_stream2buf_fu_186_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_stream2buf_fu_186_ap_start_reg <= ap_const_logic_0;
            else
                if ((((icmp_ln47_fu_232_p2 = ap_const_lv1_0) and (trunc_ln47_fu_228_p1 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2)) or ((icmp_ln47_fu_232_p2 = ap_const_lv1_0) and (trunc_ln47_fu_228_p1 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
                    grp_stream2buf_fu_186_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_stream2buf_fu_186_ap_ready = ap_const_logic_1)) then 
                    grp_stream2buf_fu_186_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    p_Val2_s_reg_150_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                p_Val2_s_reg_150 <= ap_const_lv5_0;
            elsif (((ap_const_boolean_0 = ap_block_state3_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                p_Val2_s_reg_150 <= i_reg_258;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                i_reg_258 <= i_fu_238_p2;
                trunc_ln47_reg_251 <= trunc_ln47_fu_228_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln47_fu_232_p2 = ap_const_lv1_0) and (trunc_ln47_fu_228_p1 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                icmp_ln878_1_reg_268 <= grp_fu_221_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln47_fu_232_p2 = ap_const_lv1_0) and (trunc_ln47_fu_228_p1 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                icmp_ln878_2_reg_273 <= grp_fu_221_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln47_fu_232_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                icmp_ln878_reg_263 <= icmp_ln878_fu_244_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln47_fu_232_p2, ap_CS_fsm_state3, ap_block_state3_on_subcall_done)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln47_fu_232_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((ap_const_boolean_0 = ap_block_state3_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);

    ap_block_state3_on_subcall_done_assign_proc : process(trunc_ln47_reg_251, grp_buf2stream_fu_161_ap_done, grp_stream2buf_fu_186_ap_done)
    begin
                ap_block_state3_on_subcall_done <= (((trunc_ln47_reg_251 = ap_const_lv1_1) and (grp_buf2stream_fu_161_ap_done = ap_const_logic_0)) or ((trunc_ln47_reg_251 = ap_const_lv1_1) and (grp_stream2buf_fu_186_ap_done = ap_const_logic_0)) or ((trunc_ln47_reg_251 = ap_const_lv1_0) and (grp_buf2stream_fu_161_ap_done = ap_const_logic_0)) or ((trunc_ln47_reg_251 = ap_const_lv1_0) and (grp_stream2buf_fu_186_ap_done = ap_const_logic_0)));
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_state2, icmp_ln47_fu_232_p2)
    begin
        if (((icmp_ln47_fu_232_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln47_fu_232_p2)
    begin
        if (((icmp_ln47_fu_232_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    dst_V_0_din <= grp_buf2stream_fu_161_dst_V_din;

    dst_V_0_write_assign_proc : process(trunc_ln47_reg_251, grp_buf2stream_fu_161_dst_V_write, ap_CS_fsm_state3)
    begin
        if ((((trunc_ln47_reg_251 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3)) or ((trunc_ln47_reg_251 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            dst_V_0_write <= grp_buf2stream_fu_161_dst_V_write;
        else 
            dst_V_0_write <= ap_const_logic_0;
        end if; 
    end process;

    dst_V_1_din <= grp_buf2stream_fu_161_dst_1_V_din;

    dst_V_1_write_assign_proc : process(trunc_ln47_reg_251, grp_buf2stream_fu_161_dst_1_V_write, ap_CS_fsm_state3)
    begin
        if ((((trunc_ln47_reg_251 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3)) or ((trunc_ln47_reg_251 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            dst_V_1_write <= grp_buf2stream_fu_161_dst_1_V_write;
        else 
            dst_V_1_write <= ap_const_logic_0;
        end if; 
    end process;

    dst_V_2_din <= grp_buf2stream_fu_161_dst_2_V_din;

    dst_V_2_write_assign_proc : process(trunc_ln47_reg_251, grp_buf2stream_fu_161_dst_2_V_write, ap_CS_fsm_state3)
    begin
        if ((((trunc_ln47_reg_251 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3)) or ((trunc_ln47_reg_251 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            dst_V_2_write <= grp_buf2stream_fu_161_dst_2_V_write;
        else 
            dst_V_2_write <= ap_const_logic_0;
        end if; 
    end process;

    dst_V_3_din <= grp_buf2stream_fu_161_dst_3_V_din;

    dst_V_3_write_assign_proc : process(trunc_ln47_reg_251, grp_buf2stream_fu_161_dst_3_V_write, ap_CS_fsm_state3)
    begin
        if ((((trunc_ln47_reg_251 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3)) or ((trunc_ln47_reg_251 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            dst_V_3_write <= grp_buf2stream_fu_161_dst_3_V_write;
        else 
            dst_V_3_write <= ap_const_logic_0;
        end if; 
    end process;

    dst_V_4_din <= grp_buf2stream_fu_161_dst_4_V_din;

    dst_V_4_write_assign_proc : process(trunc_ln47_reg_251, grp_buf2stream_fu_161_dst_4_V_write, ap_CS_fsm_state3)
    begin
        if ((((trunc_ln47_reg_251 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3)) or ((trunc_ln47_reg_251 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            dst_V_4_write <= grp_buf2stream_fu_161_dst_4_V_write;
        else 
            dst_V_4_write <= ap_const_logic_0;
        end if; 
    end process;

    grp_buf2stream_fu_161_ap_start <= grp_buf2stream_fu_161_ap_start_reg;

    grp_buf2stream_fu_161_buffer_0_q0_assign_proc : process(trunc_ln47_reg_251, ping_0_q0, pong_0_q0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
            if ((trunc_ln47_reg_251 = ap_const_lv1_1)) then 
                grp_buf2stream_fu_161_buffer_0_q0 <= pong_0_q0;
            elsif ((trunc_ln47_reg_251 = ap_const_lv1_0)) then 
                grp_buf2stream_fu_161_buffer_0_q0 <= ping_0_q0;
            else 
                grp_buf2stream_fu_161_buffer_0_q0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            grp_buf2stream_fu_161_buffer_0_q0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_buf2stream_fu_161_buffer_1_q0_assign_proc : process(trunc_ln47_reg_251, ping_1_q0, pong_1_q0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
            if ((trunc_ln47_reg_251 = ap_const_lv1_1)) then 
                grp_buf2stream_fu_161_buffer_1_q0 <= pong_1_q0;
            elsif ((trunc_ln47_reg_251 = ap_const_lv1_0)) then 
                grp_buf2stream_fu_161_buffer_1_q0 <= ping_1_q0;
            else 
                grp_buf2stream_fu_161_buffer_1_q0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            grp_buf2stream_fu_161_buffer_1_q0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_buf2stream_fu_161_buffer_2_q0_assign_proc : process(trunc_ln47_reg_251, ping_2_q0, pong_2_q0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
            if ((trunc_ln47_reg_251 = ap_const_lv1_1)) then 
                grp_buf2stream_fu_161_buffer_2_q0 <= pong_2_q0;
            elsif ((trunc_ln47_reg_251 = ap_const_lv1_0)) then 
                grp_buf2stream_fu_161_buffer_2_q0 <= ping_2_q0;
            else 
                grp_buf2stream_fu_161_buffer_2_q0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            grp_buf2stream_fu_161_buffer_2_q0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_buf2stream_fu_161_buffer_3_q0_assign_proc : process(trunc_ln47_reg_251, ping_3_q0, pong_3_q0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
            if ((trunc_ln47_reg_251 = ap_const_lv1_1)) then 
                grp_buf2stream_fu_161_buffer_3_q0 <= pong_3_q0;
            elsif ((trunc_ln47_reg_251 = ap_const_lv1_0)) then 
                grp_buf2stream_fu_161_buffer_3_q0 <= ping_3_q0;
            else 
                grp_buf2stream_fu_161_buffer_3_q0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            grp_buf2stream_fu_161_buffer_3_q0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_buf2stream_fu_161_buffer_4_q0_assign_proc : process(trunc_ln47_reg_251, ping_4_q0, pong_4_q0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
            if ((trunc_ln47_reg_251 = ap_const_lv1_1)) then 
                grp_buf2stream_fu_161_buffer_4_q0 <= pong_4_q0;
            elsif ((trunc_ln47_reg_251 = ap_const_lv1_0)) then 
                grp_buf2stream_fu_161_buffer_4_q0 <= ping_4_q0;
            else 
                grp_buf2stream_fu_161_buffer_4_q0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            grp_buf2stream_fu_161_buffer_4_q0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_buf2stream_fu_161_buffer_5_q0_assign_proc : process(trunc_ln47_reg_251, ping_5_q0, pong_5_q0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
            if ((trunc_ln47_reg_251 = ap_const_lv1_1)) then 
                grp_buf2stream_fu_161_buffer_5_q0 <= pong_5_q0;
            elsif ((trunc_ln47_reg_251 = ap_const_lv1_0)) then 
                grp_buf2stream_fu_161_buffer_5_q0 <= ping_5_q0;
            else 
                grp_buf2stream_fu_161_buffer_5_q0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            grp_buf2stream_fu_161_buffer_5_q0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_buf2stream_fu_161_buffer_6_q0_assign_proc : process(trunc_ln47_reg_251, ping_6_q0, pong_6_q0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
            if ((trunc_ln47_reg_251 = ap_const_lv1_1)) then 
                grp_buf2stream_fu_161_buffer_6_q0 <= pong_6_q0;
            elsif ((trunc_ln47_reg_251 = ap_const_lv1_0)) then 
                grp_buf2stream_fu_161_buffer_6_q0 <= ping_6_q0;
            else 
                grp_buf2stream_fu_161_buffer_6_q0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            grp_buf2stream_fu_161_buffer_6_q0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_buf2stream_fu_161_buffer_7_q0_assign_proc : process(trunc_ln47_reg_251, ping_7_q0, pong_7_q0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
            if ((trunc_ln47_reg_251 = ap_const_lv1_1)) then 
                grp_buf2stream_fu_161_buffer_7_q0 <= pong_7_q0;
            elsif ((trunc_ln47_reg_251 = ap_const_lv1_0)) then 
                grp_buf2stream_fu_161_buffer_7_q0 <= ping_7_q0;
            else 
                grp_buf2stream_fu_161_buffer_7_q0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            grp_buf2stream_fu_161_buffer_7_q0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_buf2stream_fu_161_buffer_8_q0_assign_proc : process(trunc_ln47_reg_251, ping_8_q0, pong_8_q0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
            if ((trunc_ln47_reg_251 = ap_const_lv1_1)) then 
                grp_buf2stream_fu_161_buffer_8_q0 <= pong_8_q0;
            elsif ((trunc_ln47_reg_251 = ap_const_lv1_0)) then 
                grp_buf2stream_fu_161_buffer_8_q0 <= ping_8_q0;
            else 
                grp_buf2stream_fu_161_buffer_8_q0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            grp_buf2stream_fu_161_buffer_8_q0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_buf2stream_fu_161_buffer_9_q0_assign_proc : process(trunc_ln47_reg_251, ping_9_q0, pong_9_q0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
            if ((trunc_ln47_reg_251 = ap_const_lv1_1)) then 
                grp_buf2stream_fu_161_buffer_9_q0 <= pong_9_q0;
            elsif ((trunc_ln47_reg_251 = ap_const_lv1_0)) then 
                grp_buf2stream_fu_161_buffer_9_q0 <= ping_9_q0;
            else 
                grp_buf2stream_fu_161_buffer_9_q0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            grp_buf2stream_fu_161_buffer_9_q0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_buf2stream_fu_161_enable_assign_proc : process(trunc_ln47_reg_251, icmp_ln878_1_reg_268, icmp_ln878_2_reg_273, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
            if ((trunc_ln47_reg_251 = ap_const_lv1_1)) then 
                grp_buf2stream_fu_161_enable <= icmp_ln878_2_reg_273(0);
            elsif ((trunc_ln47_reg_251 = ap_const_lv1_0)) then 
                grp_buf2stream_fu_161_enable <= icmp_ln878_1_reg_268(0);
            else 
                grp_buf2stream_fu_161_enable <= 'X';
            end if;
        else 
            grp_buf2stream_fu_161_enable <= 'X';
        end if; 
    end process;

    grp_fu_221_p2 <= "0" when (p_Val2_s_reg_150 = ap_const_lv5_0) else "1";
    grp_stream2buf_fu_186_ap_start <= grp_stream2buf_fu_186_ap_start_reg;
    grp_stream2buf_fu_186_enable <= icmp_ln878_reg_263(0);
    i_fu_238_p2 <= std_logic_vector(unsigned(ap_const_lv5_1) + unsigned(p_Val2_s_reg_150));
    icmp_ln47_fu_232_p2 <= "1" when (p_Val2_s_reg_150 = ap_const_lv5_10) else "0";
    icmp_ln878_fu_244_p2 <= "0" when (p_Val2_s_reg_150 = ap_const_lv5_F) else "1";

    ping_0_address0_assign_proc : process(trunc_ln47_reg_251, grp_buf2stream_fu_161_buffer_0_address0, grp_stream2buf_fu_186_buffer_0_address0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
            if ((trunc_ln47_reg_251 = ap_const_lv1_1)) then 
                ping_0_address0 <= grp_stream2buf_fu_186_buffer_0_address0;
            elsif ((trunc_ln47_reg_251 = ap_const_lv1_0)) then 
                ping_0_address0 <= grp_buf2stream_fu_161_buffer_0_address0;
            else 
                ping_0_address0 <= "XXXX";
            end if;
        else 
            ping_0_address0 <= "XXXX";
        end if; 
    end process;


    ping_0_ce0_assign_proc : process(trunc_ln47_reg_251, grp_buf2stream_fu_161_buffer_0_ce0, grp_stream2buf_fu_186_buffer_0_ce0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
            if ((trunc_ln47_reg_251 = ap_const_lv1_1)) then 
                ping_0_ce0 <= grp_stream2buf_fu_186_buffer_0_ce0;
            elsif ((trunc_ln47_reg_251 = ap_const_lv1_0)) then 
                ping_0_ce0 <= grp_buf2stream_fu_161_buffer_0_ce0;
            else 
                ping_0_ce0 <= ap_const_logic_0;
            end if;
        else 
            ping_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    ping_0_we0_assign_proc : process(trunc_ln47_reg_251, grp_stream2buf_fu_186_buffer_0_we0, ap_CS_fsm_state3)
    begin
        if (((trunc_ln47_reg_251 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ping_0_we0 <= grp_stream2buf_fu_186_buffer_0_we0;
        else 
            ping_0_we0 <= ap_const_logic_0;
        end if; 
    end process;


    ping_1_address0_assign_proc : process(trunc_ln47_reg_251, grp_buf2stream_fu_161_buffer_1_address0, grp_stream2buf_fu_186_buffer_1_address0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
            if ((trunc_ln47_reg_251 = ap_const_lv1_1)) then 
                ping_1_address0 <= grp_stream2buf_fu_186_buffer_1_address0;
            elsif ((trunc_ln47_reg_251 = ap_const_lv1_0)) then 
                ping_1_address0 <= grp_buf2stream_fu_161_buffer_1_address0;
            else 
                ping_1_address0 <= "XXXX";
            end if;
        else 
            ping_1_address0 <= "XXXX";
        end if; 
    end process;


    ping_1_ce0_assign_proc : process(trunc_ln47_reg_251, grp_buf2stream_fu_161_buffer_1_ce0, grp_stream2buf_fu_186_buffer_1_ce0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
            if ((trunc_ln47_reg_251 = ap_const_lv1_1)) then 
                ping_1_ce0 <= grp_stream2buf_fu_186_buffer_1_ce0;
            elsif ((trunc_ln47_reg_251 = ap_const_lv1_0)) then 
                ping_1_ce0 <= grp_buf2stream_fu_161_buffer_1_ce0;
            else 
                ping_1_ce0 <= ap_const_logic_0;
            end if;
        else 
            ping_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    ping_1_we0_assign_proc : process(trunc_ln47_reg_251, grp_stream2buf_fu_186_buffer_1_we0, ap_CS_fsm_state3)
    begin
        if (((trunc_ln47_reg_251 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ping_1_we0 <= grp_stream2buf_fu_186_buffer_1_we0;
        else 
            ping_1_we0 <= ap_const_logic_0;
        end if; 
    end process;


    ping_2_address0_assign_proc : process(trunc_ln47_reg_251, grp_buf2stream_fu_161_buffer_2_address0, grp_stream2buf_fu_186_buffer_2_address0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
            if ((trunc_ln47_reg_251 = ap_const_lv1_1)) then 
                ping_2_address0 <= grp_stream2buf_fu_186_buffer_2_address0;
            elsif ((trunc_ln47_reg_251 = ap_const_lv1_0)) then 
                ping_2_address0 <= grp_buf2stream_fu_161_buffer_2_address0;
            else 
                ping_2_address0 <= "XXXX";
            end if;
        else 
            ping_2_address0 <= "XXXX";
        end if; 
    end process;


    ping_2_ce0_assign_proc : process(trunc_ln47_reg_251, grp_buf2stream_fu_161_buffer_2_ce0, grp_stream2buf_fu_186_buffer_2_ce0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
            if ((trunc_ln47_reg_251 = ap_const_lv1_1)) then 
                ping_2_ce0 <= grp_stream2buf_fu_186_buffer_2_ce0;
            elsif ((trunc_ln47_reg_251 = ap_const_lv1_0)) then 
                ping_2_ce0 <= grp_buf2stream_fu_161_buffer_2_ce0;
            else 
                ping_2_ce0 <= ap_const_logic_0;
            end if;
        else 
            ping_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    ping_2_we0_assign_proc : process(trunc_ln47_reg_251, grp_stream2buf_fu_186_buffer_2_we0, ap_CS_fsm_state3)
    begin
        if (((trunc_ln47_reg_251 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ping_2_we0 <= grp_stream2buf_fu_186_buffer_2_we0;
        else 
            ping_2_we0 <= ap_const_logic_0;
        end if; 
    end process;


    ping_3_address0_assign_proc : process(trunc_ln47_reg_251, grp_buf2stream_fu_161_buffer_3_address0, grp_stream2buf_fu_186_buffer_3_address0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
            if ((trunc_ln47_reg_251 = ap_const_lv1_1)) then 
                ping_3_address0 <= grp_stream2buf_fu_186_buffer_3_address0;
            elsif ((trunc_ln47_reg_251 = ap_const_lv1_0)) then 
                ping_3_address0 <= grp_buf2stream_fu_161_buffer_3_address0;
            else 
                ping_3_address0 <= "XXXX";
            end if;
        else 
            ping_3_address0 <= "XXXX";
        end if; 
    end process;


    ping_3_ce0_assign_proc : process(trunc_ln47_reg_251, grp_buf2stream_fu_161_buffer_3_ce0, grp_stream2buf_fu_186_buffer_3_ce0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
            if ((trunc_ln47_reg_251 = ap_const_lv1_1)) then 
                ping_3_ce0 <= grp_stream2buf_fu_186_buffer_3_ce0;
            elsif ((trunc_ln47_reg_251 = ap_const_lv1_0)) then 
                ping_3_ce0 <= grp_buf2stream_fu_161_buffer_3_ce0;
            else 
                ping_3_ce0 <= ap_const_logic_0;
            end if;
        else 
            ping_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    ping_3_we0_assign_proc : process(trunc_ln47_reg_251, grp_stream2buf_fu_186_buffer_3_we0, ap_CS_fsm_state3)
    begin
        if (((trunc_ln47_reg_251 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ping_3_we0 <= grp_stream2buf_fu_186_buffer_3_we0;
        else 
            ping_3_we0 <= ap_const_logic_0;
        end if; 
    end process;


    ping_4_address0_assign_proc : process(trunc_ln47_reg_251, grp_buf2stream_fu_161_buffer_4_address0, grp_stream2buf_fu_186_buffer_4_address0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
            if ((trunc_ln47_reg_251 = ap_const_lv1_1)) then 
                ping_4_address0 <= grp_stream2buf_fu_186_buffer_4_address0;
            elsif ((trunc_ln47_reg_251 = ap_const_lv1_0)) then 
                ping_4_address0 <= grp_buf2stream_fu_161_buffer_4_address0;
            else 
                ping_4_address0 <= "XXXX";
            end if;
        else 
            ping_4_address0 <= "XXXX";
        end if; 
    end process;


    ping_4_ce0_assign_proc : process(trunc_ln47_reg_251, grp_buf2stream_fu_161_buffer_4_ce0, grp_stream2buf_fu_186_buffer_4_ce0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
            if ((trunc_ln47_reg_251 = ap_const_lv1_1)) then 
                ping_4_ce0 <= grp_stream2buf_fu_186_buffer_4_ce0;
            elsif ((trunc_ln47_reg_251 = ap_const_lv1_0)) then 
                ping_4_ce0 <= grp_buf2stream_fu_161_buffer_4_ce0;
            else 
                ping_4_ce0 <= ap_const_logic_0;
            end if;
        else 
            ping_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    ping_4_we0_assign_proc : process(trunc_ln47_reg_251, grp_stream2buf_fu_186_buffer_4_we0, ap_CS_fsm_state3)
    begin
        if (((trunc_ln47_reg_251 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ping_4_we0 <= grp_stream2buf_fu_186_buffer_4_we0;
        else 
            ping_4_we0 <= ap_const_logic_0;
        end if; 
    end process;


    ping_5_address0_assign_proc : process(trunc_ln47_reg_251, grp_buf2stream_fu_161_buffer_5_address0, grp_stream2buf_fu_186_buffer_5_address0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
            if ((trunc_ln47_reg_251 = ap_const_lv1_1)) then 
                ping_5_address0 <= grp_stream2buf_fu_186_buffer_5_address0;
            elsif ((trunc_ln47_reg_251 = ap_const_lv1_0)) then 
                ping_5_address0 <= grp_buf2stream_fu_161_buffer_5_address0;
            else 
                ping_5_address0 <= "XXXX";
            end if;
        else 
            ping_5_address0 <= "XXXX";
        end if; 
    end process;


    ping_5_ce0_assign_proc : process(trunc_ln47_reg_251, grp_buf2stream_fu_161_buffer_5_ce0, grp_stream2buf_fu_186_buffer_5_ce0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
            if ((trunc_ln47_reg_251 = ap_const_lv1_1)) then 
                ping_5_ce0 <= grp_stream2buf_fu_186_buffer_5_ce0;
            elsif ((trunc_ln47_reg_251 = ap_const_lv1_0)) then 
                ping_5_ce0 <= grp_buf2stream_fu_161_buffer_5_ce0;
            else 
                ping_5_ce0 <= ap_const_logic_0;
            end if;
        else 
            ping_5_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    ping_5_we0_assign_proc : process(trunc_ln47_reg_251, grp_stream2buf_fu_186_buffer_5_we0, ap_CS_fsm_state3)
    begin
        if (((trunc_ln47_reg_251 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ping_5_we0 <= grp_stream2buf_fu_186_buffer_5_we0;
        else 
            ping_5_we0 <= ap_const_logic_0;
        end if; 
    end process;


    ping_6_address0_assign_proc : process(trunc_ln47_reg_251, grp_buf2stream_fu_161_buffer_6_address0, grp_stream2buf_fu_186_buffer_6_address0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
            if ((trunc_ln47_reg_251 = ap_const_lv1_1)) then 
                ping_6_address0 <= grp_stream2buf_fu_186_buffer_6_address0;
            elsif ((trunc_ln47_reg_251 = ap_const_lv1_0)) then 
                ping_6_address0 <= grp_buf2stream_fu_161_buffer_6_address0;
            else 
                ping_6_address0 <= "XXXX";
            end if;
        else 
            ping_6_address0 <= "XXXX";
        end if; 
    end process;


    ping_6_ce0_assign_proc : process(trunc_ln47_reg_251, grp_buf2stream_fu_161_buffer_6_ce0, grp_stream2buf_fu_186_buffer_6_ce0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
            if ((trunc_ln47_reg_251 = ap_const_lv1_1)) then 
                ping_6_ce0 <= grp_stream2buf_fu_186_buffer_6_ce0;
            elsif ((trunc_ln47_reg_251 = ap_const_lv1_0)) then 
                ping_6_ce0 <= grp_buf2stream_fu_161_buffer_6_ce0;
            else 
                ping_6_ce0 <= ap_const_logic_0;
            end if;
        else 
            ping_6_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    ping_6_we0_assign_proc : process(trunc_ln47_reg_251, grp_stream2buf_fu_186_buffer_6_we0, ap_CS_fsm_state3)
    begin
        if (((trunc_ln47_reg_251 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ping_6_we0 <= grp_stream2buf_fu_186_buffer_6_we0;
        else 
            ping_6_we0 <= ap_const_logic_0;
        end if; 
    end process;


    ping_7_address0_assign_proc : process(trunc_ln47_reg_251, grp_buf2stream_fu_161_buffer_7_address0, grp_stream2buf_fu_186_buffer_7_address0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
            if ((trunc_ln47_reg_251 = ap_const_lv1_1)) then 
                ping_7_address0 <= grp_stream2buf_fu_186_buffer_7_address0;
            elsif ((trunc_ln47_reg_251 = ap_const_lv1_0)) then 
                ping_7_address0 <= grp_buf2stream_fu_161_buffer_7_address0;
            else 
                ping_7_address0 <= "XXXX";
            end if;
        else 
            ping_7_address0 <= "XXXX";
        end if; 
    end process;


    ping_7_ce0_assign_proc : process(trunc_ln47_reg_251, grp_buf2stream_fu_161_buffer_7_ce0, grp_stream2buf_fu_186_buffer_7_ce0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
            if ((trunc_ln47_reg_251 = ap_const_lv1_1)) then 
                ping_7_ce0 <= grp_stream2buf_fu_186_buffer_7_ce0;
            elsif ((trunc_ln47_reg_251 = ap_const_lv1_0)) then 
                ping_7_ce0 <= grp_buf2stream_fu_161_buffer_7_ce0;
            else 
                ping_7_ce0 <= ap_const_logic_0;
            end if;
        else 
            ping_7_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    ping_7_we0_assign_proc : process(trunc_ln47_reg_251, grp_stream2buf_fu_186_buffer_7_we0, ap_CS_fsm_state3)
    begin
        if (((trunc_ln47_reg_251 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ping_7_we0 <= grp_stream2buf_fu_186_buffer_7_we0;
        else 
            ping_7_we0 <= ap_const_logic_0;
        end if; 
    end process;


    ping_8_address0_assign_proc : process(trunc_ln47_reg_251, grp_buf2stream_fu_161_buffer_8_address0, grp_stream2buf_fu_186_buffer_8_address0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
            if ((trunc_ln47_reg_251 = ap_const_lv1_1)) then 
                ping_8_address0 <= grp_stream2buf_fu_186_buffer_8_address0;
            elsif ((trunc_ln47_reg_251 = ap_const_lv1_0)) then 
                ping_8_address0 <= grp_buf2stream_fu_161_buffer_8_address0;
            else 
                ping_8_address0 <= "XXXX";
            end if;
        else 
            ping_8_address0 <= "XXXX";
        end if; 
    end process;


    ping_8_ce0_assign_proc : process(trunc_ln47_reg_251, grp_buf2stream_fu_161_buffer_8_ce0, grp_stream2buf_fu_186_buffer_8_ce0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
            if ((trunc_ln47_reg_251 = ap_const_lv1_1)) then 
                ping_8_ce0 <= grp_stream2buf_fu_186_buffer_8_ce0;
            elsif ((trunc_ln47_reg_251 = ap_const_lv1_0)) then 
                ping_8_ce0 <= grp_buf2stream_fu_161_buffer_8_ce0;
            else 
                ping_8_ce0 <= ap_const_logic_0;
            end if;
        else 
            ping_8_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    ping_8_we0_assign_proc : process(trunc_ln47_reg_251, grp_stream2buf_fu_186_buffer_8_we0, ap_CS_fsm_state3)
    begin
        if (((trunc_ln47_reg_251 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ping_8_we0 <= grp_stream2buf_fu_186_buffer_8_we0;
        else 
            ping_8_we0 <= ap_const_logic_0;
        end if; 
    end process;


    ping_9_address0_assign_proc : process(trunc_ln47_reg_251, grp_buf2stream_fu_161_buffer_9_address0, grp_stream2buf_fu_186_buffer_9_address0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
            if ((trunc_ln47_reg_251 = ap_const_lv1_1)) then 
                ping_9_address0 <= grp_stream2buf_fu_186_buffer_9_address0;
            elsif ((trunc_ln47_reg_251 = ap_const_lv1_0)) then 
                ping_9_address0 <= grp_buf2stream_fu_161_buffer_9_address0;
            else 
                ping_9_address0 <= "XXXX";
            end if;
        else 
            ping_9_address0 <= "XXXX";
        end if; 
    end process;


    ping_9_ce0_assign_proc : process(trunc_ln47_reg_251, grp_buf2stream_fu_161_buffer_9_ce0, grp_stream2buf_fu_186_buffer_9_ce0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
            if ((trunc_ln47_reg_251 = ap_const_lv1_1)) then 
                ping_9_ce0 <= grp_stream2buf_fu_186_buffer_9_ce0;
            elsif ((trunc_ln47_reg_251 = ap_const_lv1_0)) then 
                ping_9_ce0 <= grp_buf2stream_fu_161_buffer_9_ce0;
            else 
                ping_9_ce0 <= ap_const_logic_0;
            end if;
        else 
            ping_9_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    ping_9_we0_assign_proc : process(trunc_ln47_reg_251, grp_stream2buf_fu_186_buffer_9_we0, ap_CS_fsm_state3)
    begin
        if (((trunc_ln47_reg_251 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ping_9_we0 <= grp_stream2buf_fu_186_buffer_9_we0;
        else 
            ping_9_we0 <= ap_const_logic_0;
        end if; 
    end process;


    pong_0_address0_assign_proc : process(trunc_ln47_reg_251, grp_buf2stream_fu_161_buffer_0_address0, grp_stream2buf_fu_186_buffer_0_address0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
            if ((trunc_ln47_reg_251 = ap_const_lv1_0)) then 
                pong_0_address0 <= grp_stream2buf_fu_186_buffer_0_address0;
            elsif ((trunc_ln47_reg_251 = ap_const_lv1_1)) then 
                pong_0_address0 <= grp_buf2stream_fu_161_buffer_0_address0;
            else 
                pong_0_address0 <= "XXXX";
            end if;
        else 
            pong_0_address0 <= "XXXX";
        end if; 
    end process;


    pong_0_ce0_assign_proc : process(trunc_ln47_reg_251, grp_buf2stream_fu_161_buffer_0_ce0, grp_stream2buf_fu_186_buffer_0_ce0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
            if ((trunc_ln47_reg_251 = ap_const_lv1_0)) then 
                pong_0_ce0 <= grp_stream2buf_fu_186_buffer_0_ce0;
            elsif ((trunc_ln47_reg_251 = ap_const_lv1_1)) then 
                pong_0_ce0 <= grp_buf2stream_fu_161_buffer_0_ce0;
            else 
                pong_0_ce0 <= ap_const_logic_0;
            end if;
        else 
            pong_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    pong_0_we0_assign_proc : process(trunc_ln47_reg_251, grp_stream2buf_fu_186_buffer_0_we0, ap_CS_fsm_state3)
    begin
        if (((trunc_ln47_reg_251 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            pong_0_we0 <= grp_stream2buf_fu_186_buffer_0_we0;
        else 
            pong_0_we0 <= ap_const_logic_0;
        end if; 
    end process;


    pong_1_address0_assign_proc : process(trunc_ln47_reg_251, grp_buf2stream_fu_161_buffer_1_address0, grp_stream2buf_fu_186_buffer_1_address0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
            if ((trunc_ln47_reg_251 = ap_const_lv1_0)) then 
                pong_1_address0 <= grp_stream2buf_fu_186_buffer_1_address0;
            elsif ((trunc_ln47_reg_251 = ap_const_lv1_1)) then 
                pong_1_address0 <= grp_buf2stream_fu_161_buffer_1_address0;
            else 
                pong_1_address0 <= "XXXX";
            end if;
        else 
            pong_1_address0 <= "XXXX";
        end if; 
    end process;


    pong_1_ce0_assign_proc : process(trunc_ln47_reg_251, grp_buf2stream_fu_161_buffer_1_ce0, grp_stream2buf_fu_186_buffer_1_ce0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
            if ((trunc_ln47_reg_251 = ap_const_lv1_0)) then 
                pong_1_ce0 <= grp_stream2buf_fu_186_buffer_1_ce0;
            elsif ((trunc_ln47_reg_251 = ap_const_lv1_1)) then 
                pong_1_ce0 <= grp_buf2stream_fu_161_buffer_1_ce0;
            else 
                pong_1_ce0 <= ap_const_logic_0;
            end if;
        else 
            pong_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    pong_1_we0_assign_proc : process(trunc_ln47_reg_251, grp_stream2buf_fu_186_buffer_1_we0, ap_CS_fsm_state3)
    begin
        if (((trunc_ln47_reg_251 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            pong_1_we0 <= grp_stream2buf_fu_186_buffer_1_we0;
        else 
            pong_1_we0 <= ap_const_logic_0;
        end if; 
    end process;


    pong_2_address0_assign_proc : process(trunc_ln47_reg_251, grp_buf2stream_fu_161_buffer_2_address0, grp_stream2buf_fu_186_buffer_2_address0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
            if ((trunc_ln47_reg_251 = ap_const_lv1_0)) then 
                pong_2_address0 <= grp_stream2buf_fu_186_buffer_2_address0;
            elsif ((trunc_ln47_reg_251 = ap_const_lv1_1)) then 
                pong_2_address0 <= grp_buf2stream_fu_161_buffer_2_address0;
            else 
                pong_2_address0 <= "XXXX";
            end if;
        else 
            pong_2_address0 <= "XXXX";
        end if; 
    end process;


    pong_2_ce0_assign_proc : process(trunc_ln47_reg_251, grp_buf2stream_fu_161_buffer_2_ce0, grp_stream2buf_fu_186_buffer_2_ce0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
            if ((trunc_ln47_reg_251 = ap_const_lv1_0)) then 
                pong_2_ce0 <= grp_stream2buf_fu_186_buffer_2_ce0;
            elsif ((trunc_ln47_reg_251 = ap_const_lv1_1)) then 
                pong_2_ce0 <= grp_buf2stream_fu_161_buffer_2_ce0;
            else 
                pong_2_ce0 <= ap_const_logic_0;
            end if;
        else 
            pong_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    pong_2_we0_assign_proc : process(trunc_ln47_reg_251, grp_stream2buf_fu_186_buffer_2_we0, ap_CS_fsm_state3)
    begin
        if (((trunc_ln47_reg_251 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            pong_2_we0 <= grp_stream2buf_fu_186_buffer_2_we0;
        else 
            pong_2_we0 <= ap_const_logic_0;
        end if; 
    end process;


    pong_3_address0_assign_proc : process(trunc_ln47_reg_251, grp_buf2stream_fu_161_buffer_3_address0, grp_stream2buf_fu_186_buffer_3_address0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
            if ((trunc_ln47_reg_251 = ap_const_lv1_0)) then 
                pong_3_address0 <= grp_stream2buf_fu_186_buffer_3_address0;
            elsif ((trunc_ln47_reg_251 = ap_const_lv1_1)) then 
                pong_3_address0 <= grp_buf2stream_fu_161_buffer_3_address0;
            else 
                pong_3_address0 <= "XXXX";
            end if;
        else 
            pong_3_address0 <= "XXXX";
        end if; 
    end process;


    pong_3_ce0_assign_proc : process(trunc_ln47_reg_251, grp_buf2stream_fu_161_buffer_3_ce0, grp_stream2buf_fu_186_buffer_3_ce0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
            if ((trunc_ln47_reg_251 = ap_const_lv1_0)) then 
                pong_3_ce0 <= grp_stream2buf_fu_186_buffer_3_ce0;
            elsif ((trunc_ln47_reg_251 = ap_const_lv1_1)) then 
                pong_3_ce0 <= grp_buf2stream_fu_161_buffer_3_ce0;
            else 
                pong_3_ce0 <= ap_const_logic_0;
            end if;
        else 
            pong_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    pong_3_we0_assign_proc : process(trunc_ln47_reg_251, grp_stream2buf_fu_186_buffer_3_we0, ap_CS_fsm_state3)
    begin
        if (((trunc_ln47_reg_251 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            pong_3_we0 <= grp_stream2buf_fu_186_buffer_3_we0;
        else 
            pong_3_we0 <= ap_const_logic_0;
        end if; 
    end process;


    pong_4_address0_assign_proc : process(trunc_ln47_reg_251, grp_buf2stream_fu_161_buffer_4_address0, grp_stream2buf_fu_186_buffer_4_address0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
            if ((trunc_ln47_reg_251 = ap_const_lv1_0)) then 
                pong_4_address0 <= grp_stream2buf_fu_186_buffer_4_address0;
            elsif ((trunc_ln47_reg_251 = ap_const_lv1_1)) then 
                pong_4_address0 <= grp_buf2stream_fu_161_buffer_4_address0;
            else 
                pong_4_address0 <= "XXXX";
            end if;
        else 
            pong_4_address0 <= "XXXX";
        end if; 
    end process;


    pong_4_ce0_assign_proc : process(trunc_ln47_reg_251, grp_buf2stream_fu_161_buffer_4_ce0, grp_stream2buf_fu_186_buffer_4_ce0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
            if ((trunc_ln47_reg_251 = ap_const_lv1_0)) then 
                pong_4_ce0 <= grp_stream2buf_fu_186_buffer_4_ce0;
            elsif ((trunc_ln47_reg_251 = ap_const_lv1_1)) then 
                pong_4_ce0 <= grp_buf2stream_fu_161_buffer_4_ce0;
            else 
                pong_4_ce0 <= ap_const_logic_0;
            end if;
        else 
            pong_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    pong_4_we0_assign_proc : process(trunc_ln47_reg_251, grp_stream2buf_fu_186_buffer_4_we0, ap_CS_fsm_state3)
    begin
        if (((trunc_ln47_reg_251 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            pong_4_we0 <= grp_stream2buf_fu_186_buffer_4_we0;
        else 
            pong_4_we0 <= ap_const_logic_0;
        end if; 
    end process;


    pong_5_address0_assign_proc : process(trunc_ln47_reg_251, grp_buf2stream_fu_161_buffer_5_address0, grp_stream2buf_fu_186_buffer_5_address0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
            if ((trunc_ln47_reg_251 = ap_const_lv1_0)) then 
                pong_5_address0 <= grp_stream2buf_fu_186_buffer_5_address0;
            elsif ((trunc_ln47_reg_251 = ap_const_lv1_1)) then 
                pong_5_address0 <= grp_buf2stream_fu_161_buffer_5_address0;
            else 
                pong_5_address0 <= "XXXX";
            end if;
        else 
            pong_5_address0 <= "XXXX";
        end if; 
    end process;


    pong_5_ce0_assign_proc : process(trunc_ln47_reg_251, grp_buf2stream_fu_161_buffer_5_ce0, grp_stream2buf_fu_186_buffer_5_ce0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
            if ((trunc_ln47_reg_251 = ap_const_lv1_0)) then 
                pong_5_ce0 <= grp_stream2buf_fu_186_buffer_5_ce0;
            elsif ((trunc_ln47_reg_251 = ap_const_lv1_1)) then 
                pong_5_ce0 <= grp_buf2stream_fu_161_buffer_5_ce0;
            else 
                pong_5_ce0 <= ap_const_logic_0;
            end if;
        else 
            pong_5_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    pong_5_we0_assign_proc : process(trunc_ln47_reg_251, grp_stream2buf_fu_186_buffer_5_we0, ap_CS_fsm_state3)
    begin
        if (((trunc_ln47_reg_251 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            pong_5_we0 <= grp_stream2buf_fu_186_buffer_5_we0;
        else 
            pong_5_we0 <= ap_const_logic_0;
        end if; 
    end process;


    pong_6_address0_assign_proc : process(trunc_ln47_reg_251, grp_buf2stream_fu_161_buffer_6_address0, grp_stream2buf_fu_186_buffer_6_address0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
            if ((trunc_ln47_reg_251 = ap_const_lv1_0)) then 
                pong_6_address0 <= grp_stream2buf_fu_186_buffer_6_address0;
            elsif ((trunc_ln47_reg_251 = ap_const_lv1_1)) then 
                pong_6_address0 <= grp_buf2stream_fu_161_buffer_6_address0;
            else 
                pong_6_address0 <= "XXXX";
            end if;
        else 
            pong_6_address0 <= "XXXX";
        end if; 
    end process;


    pong_6_ce0_assign_proc : process(trunc_ln47_reg_251, grp_buf2stream_fu_161_buffer_6_ce0, grp_stream2buf_fu_186_buffer_6_ce0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
            if ((trunc_ln47_reg_251 = ap_const_lv1_0)) then 
                pong_6_ce0 <= grp_stream2buf_fu_186_buffer_6_ce0;
            elsif ((trunc_ln47_reg_251 = ap_const_lv1_1)) then 
                pong_6_ce0 <= grp_buf2stream_fu_161_buffer_6_ce0;
            else 
                pong_6_ce0 <= ap_const_logic_0;
            end if;
        else 
            pong_6_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    pong_6_we0_assign_proc : process(trunc_ln47_reg_251, grp_stream2buf_fu_186_buffer_6_we0, ap_CS_fsm_state3)
    begin
        if (((trunc_ln47_reg_251 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            pong_6_we0 <= grp_stream2buf_fu_186_buffer_6_we0;
        else 
            pong_6_we0 <= ap_const_logic_0;
        end if; 
    end process;


    pong_7_address0_assign_proc : process(trunc_ln47_reg_251, grp_buf2stream_fu_161_buffer_7_address0, grp_stream2buf_fu_186_buffer_7_address0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
            if ((trunc_ln47_reg_251 = ap_const_lv1_0)) then 
                pong_7_address0 <= grp_stream2buf_fu_186_buffer_7_address0;
            elsif ((trunc_ln47_reg_251 = ap_const_lv1_1)) then 
                pong_7_address0 <= grp_buf2stream_fu_161_buffer_7_address0;
            else 
                pong_7_address0 <= "XXXX";
            end if;
        else 
            pong_7_address0 <= "XXXX";
        end if; 
    end process;


    pong_7_ce0_assign_proc : process(trunc_ln47_reg_251, grp_buf2stream_fu_161_buffer_7_ce0, grp_stream2buf_fu_186_buffer_7_ce0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
            if ((trunc_ln47_reg_251 = ap_const_lv1_0)) then 
                pong_7_ce0 <= grp_stream2buf_fu_186_buffer_7_ce0;
            elsif ((trunc_ln47_reg_251 = ap_const_lv1_1)) then 
                pong_7_ce0 <= grp_buf2stream_fu_161_buffer_7_ce0;
            else 
                pong_7_ce0 <= ap_const_logic_0;
            end if;
        else 
            pong_7_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    pong_7_we0_assign_proc : process(trunc_ln47_reg_251, grp_stream2buf_fu_186_buffer_7_we0, ap_CS_fsm_state3)
    begin
        if (((trunc_ln47_reg_251 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            pong_7_we0 <= grp_stream2buf_fu_186_buffer_7_we0;
        else 
            pong_7_we0 <= ap_const_logic_0;
        end if; 
    end process;


    pong_8_address0_assign_proc : process(trunc_ln47_reg_251, grp_buf2stream_fu_161_buffer_8_address0, grp_stream2buf_fu_186_buffer_8_address0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
            if ((trunc_ln47_reg_251 = ap_const_lv1_0)) then 
                pong_8_address0 <= grp_stream2buf_fu_186_buffer_8_address0;
            elsif ((trunc_ln47_reg_251 = ap_const_lv1_1)) then 
                pong_8_address0 <= grp_buf2stream_fu_161_buffer_8_address0;
            else 
                pong_8_address0 <= "XXXX";
            end if;
        else 
            pong_8_address0 <= "XXXX";
        end if; 
    end process;


    pong_8_ce0_assign_proc : process(trunc_ln47_reg_251, grp_buf2stream_fu_161_buffer_8_ce0, grp_stream2buf_fu_186_buffer_8_ce0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
            if ((trunc_ln47_reg_251 = ap_const_lv1_0)) then 
                pong_8_ce0 <= grp_stream2buf_fu_186_buffer_8_ce0;
            elsif ((trunc_ln47_reg_251 = ap_const_lv1_1)) then 
                pong_8_ce0 <= grp_buf2stream_fu_161_buffer_8_ce0;
            else 
                pong_8_ce0 <= ap_const_logic_0;
            end if;
        else 
            pong_8_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    pong_8_we0_assign_proc : process(trunc_ln47_reg_251, grp_stream2buf_fu_186_buffer_8_we0, ap_CS_fsm_state3)
    begin
        if (((trunc_ln47_reg_251 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            pong_8_we0 <= grp_stream2buf_fu_186_buffer_8_we0;
        else 
            pong_8_we0 <= ap_const_logic_0;
        end if; 
    end process;


    pong_9_address0_assign_proc : process(trunc_ln47_reg_251, grp_buf2stream_fu_161_buffer_9_address0, grp_stream2buf_fu_186_buffer_9_address0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
            if ((trunc_ln47_reg_251 = ap_const_lv1_0)) then 
                pong_9_address0 <= grp_stream2buf_fu_186_buffer_9_address0;
            elsif ((trunc_ln47_reg_251 = ap_const_lv1_1)) then 
                pong_9_address0 <= grp_buf2stream_fu_161_buffer_9_address0;
            else 
                pong_9_address0 <= "XXXX";
            end if;
        else 
            pong_9_address0 <= "XXXX";
        end if; 
    end process;


    pong_9_ce0_assign_proc : process(trunc_ln47_reg_251, grp_buf2stream_fu_161_buffer_9_ce0, grp_stream2buf_fu_186_buffer_9_ce0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
            if ((trunc_ln47_reg_251 = ap_const_lv1_0)) then 
                pong_9_ce0 <= grp_stream2buf_fu_186_buffer_9_ce0;
            elsif ((trunc_ln47_reg_251 = ap_const_lv1_1)) then 
                pong_9_ce0 <= grp_buf2stream_fu_161_buffer_9_ce0;
            else 
                pong_9_ce0 <= ap_const_logic_0;
            end if;
        else 
            pong_9_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    pong_9_we0_assign_proc : process(trunc_ln47_reg_251, grp_stream2buf_fu_186_buffer_9_we0, ap_CS_fsm_state3)
    begin
        if (((trunc_ln47_reg_251 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            pong_9_we0 <= grp_stream2buf_fu_186_buffer_9_we0;
        else 
            pong_9_we0 <= ap_const_logic_0;
        end if; 
    end process;


    src_V_0_read_assign_proc : process(trunc_ln47_reg_251, grp_stream2buf_fu_186_src_V_read, ap_CS_fsm_state3)
    begin
        if ((((trunc_ln47_reg_251 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3)) or ((trunc_ln47_reg_251 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            src_V_0_read <= grp_stream2buf_fu_186_src_V_read;
        else 
            src_V_0_read <= ap_const_logic_0;
        end if; 
    end process;


    src_V_1_read_assign_proc : process(trunc_ln47_reg_251, grp_stream2buf_fu_186_src_1_V_read, ap_CS_fsm_state3)
    begin
        if ((((trunc_ln47_reg_251 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3)) or ((trunc_ln47_reg_251 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            src_V_1_read <= grp_stream2buf_fu_186_src_1_V_read;
        else 
            src_V_1_read <= ap_const_logic_0;
        end if; 
    end process;


    src_V_2_read_assign_proc : process(trunc_ln47_reg_251, grp_stream2buf_fu_186_src_2_V_read, ap_CS_fsm_state3)
    begin
        if ((((trunc_ln47_reg_251 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3)) or ((trunc_ln47_reg_251 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            src_V_2_read <= grp_stream2buf_fu_186_src_2_V_read;
        else 
            src_V_2_read <= ap_const_logic_0;
        end if; 
    end process;


    src_V_3_read_assign_proc : process(trunc_ln47_reg_251, grp_stream2buf_fu_186_src_3_V_read, ap_CS_fsm_state3)
    begin
        if ((((trunc_ln47_reg_251 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3)) or ((trunc_ln47_reg_251 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            src_V_3_read <= grp_stream2buf_fu_186_src_3_V_read;
        else 
            src_V_3_read <= ap_const_logic_0;
        end if; 
    end process;


    src_V_4_read_assign_proc : process(trunc_ln47_reg_251, grp_stream2buf_fu_186_src_4_V_read, ap_CS_fsm_state3)
    begin
        if ((((trunc_ln47_reg_251 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3)) or ((trunc_ln47_reg_251 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            src_V_4_read <= grp_stream2buf_fu_186_src_4_V_read;
        else 
            src_V_4_read <= ap_const_logic_0;
        end if; 
    end process;


    src_V_5_read_assign_proc : process(trunc_ln47_reg_251, grp_stream2buf_fu_186_src_5_V_read, ap_CS_fsm_state3)
    begin
        if ((((trunc_ln47_reg_251 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3)) or ((trunc_ln47_reg_251 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            src_V_5_read <= grp_stream2buf_fu_186_src_5_V_read;
        else 
            src_V_5_read <= ap_const_logic_0;
        end if; 
    end process;


    src_V_6_read_assign_proc : process(trunc_ln47_reg_251, grp_stream2buf_fu_186_src_6_V_read, ap_CS_fsm_state3)
    begin
        if ((((trunc_ln47_reg_251 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3)) or ((trunc_ln47_reg_251 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            src_V_6_read <= grp_stream2buf_fu_186_src_6_V_read;
        else 
            src_V_6_read <= ap_const_logic_0;
        end if; 
    end process;


    src_V_7_read_assign_proc : process(trunc_ln47_reg_251, grp_stream2buf_fu_186_src_7_V_read, ap_CS_fsm_state3)
    begin
        if ((((trunc_ln47_reg_251 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3)) or ((trunc_ln47_reg_251 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            src_V_7_read <= grp_stream2buf_fu_186_src_7_V_read;
        else 
            src_V_7_read <= ap_const_logic_0;
        end if; 
    end process;


    src_V_8_read_assign_proc : process(trunc_ln47_reg_251, grp_stream2buf_fu_186_src_8_V_read, ap_CS_fsm_state3)
    begin
        if ((((trunc_ln47_reg_251 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3)) or ((trunc_ln47_reg_251 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            src_V_8_read <= grp_stream2buf_fu_186_src_8_V_read;
        else 
            src_V_8_read <= ap_const_logic_0;
        end if; 
    end process;


    src_V_9_read_assign_proc : process(trunc_ln47_reg_251, grp_stream2buf_fu_186_src_9_V_read, ap_CS_fsm_state3)
    begin
        if ((((trunc_ln47_reg_251 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3)) or ((trunc_ln47_reg_251 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            src_V_9_read <= grp_stream2buf_fu_186_src_9_V_read;
        else 
            src_V_9_read <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln47_fu_228_p1 <= p_Val2_s_reg_150(1 - 1 downto 0);
end behav;
