// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="top_top,hls_ip_2020_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu7ev-ffvc1156-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.969000,HLS_SYN_LAT=225,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=1327,HLS_SYN_LUT=1626,HLS_VERSION=2020_1}" *)

module top (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        src_V_0_dout,
        src_V_0_empty_n,
        src_V_0_read,
        src_V_1_dout,
        src_V_1_empty_n,
        src_V_1_read,
        src_V_2_dout,
        src_V_2_empty_n,
        src_V_2_read,
        src_V_3_dout,
        src_V_3_empty_n,
        src_V_3_read,
        src_V_4_dout,
        src_V_4_empty_n,
        src_V_4_read,
        src_V_5_dout,
        src_V_5_empty_n,
        src_V_5_read,
        src_V_6_dout,
        src_V_6_empty_n,
        src_V_6_read,
        src_V_7_dout,
        src_V_7_empty_n,
        src_V_7_read,
        src_V_8_dout,
        src_V_8_empty_n,
        src_V_8_read,
        src_V_9_dout,
        src_V_9_empty_n,
        src_V_9_read,
        dst_V_0_din,
        dst_V_0_full_n,
        dst_V_0_write,
        dst_V_1_din,
        dst_V_1_full_n,
        dst_V_1_write,
        dst_V_2_din,
        dst_V_2_full_n,
        dst_V_2_write,
        dst_V_3_din,
        dst_V_3_full_n,
        dst_V_3_write,
        dst_V_4_din,
        dst_V_4_full_n,
        dst_V_4_write
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] src_V_0_dout;
input   src_V_0_empty_n;
output   src_V_0_read;
input  [31:0] src_V_1_dout;
input   src_V_1_empty_n;
output   src_V_1_read;
input  [31:0] src_V_2_dout;
input   src_V_2_empty_n;
output   src_V_2_read;
input  [31:0] src_V_3_dout;
input   src_V_3_empty_n;
output   src_V_3_read;
input  [31:0] src_V_4_dout;
input   src_V_4_empty_n;
output   src_V_4_read;
input  [31:0] src_V_5_dout;
input   src_V_5_empty_n;
output   src_V_5_read;
input  [31:0] src_V_6_dout;
input   src_V_6_empty_n;
output   src_V_6_read;
input  [31:0] src_V_7_dout;
input   src_V_7_empty_n;
output   src_V_7_read;
input  [31:0] src_V_8_dout;
input   src_V_8_empty_n;
output   src_V_8_read;
input  [31:0] src_V_9_dout;
input   src_V_9_empty_n;
output   src_V_9_read;
output  [31:0] dst_V_0_din;
input   dst_V_0_full_n;
output   dst_V_0_write;
output  [31:0] dst_V_1_din;
input   dst_V_1_full_n;
output   dst_V_1_write;
output  [31:0] dst_V_2_din;
input   dst_V_2_full_n;
output   dst_V_2_write;
output  [31:0] dst_V_3_din;
input   dst_V_3_full_n;
output   dst_V_3_write;
output  [31:0] dst_V_4_din;
input   dst_V_4_full_n;
output   dst_V_4_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg src_V_0_read;
reg src_V_1_read;
reg src_V_2_read;
reg src_V_3_read;
reg src_V_4_read;
reg src_V_5_read;
reg src_V_6_read;
reg src_V_7_read;
reg src_V_8_read;
reg src_V_9_read;
reg dst_V_0_write;
reg dst_V_1_write;
reg dst_V_2_write;
reg dst_V_3_write;
reg dst_V_4_write;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] trunc_ln47_fu_228_p1;
reg   [0:0] trunc_ln47_reg_251;
wire    ap_CS_fsm_state2;
wire   [4:0] i_fu_238_p2;
reg   [4:0] i_reg_258;
wire   [0:0] icmp_ln878_fu_244_p2;
reg   [0:0] icmp_ln878_reg_263;
wire   [0:0] icmp_ln47_fu_232_p2;
wire   [0:0] grp_fu_221_p2;
reg   [0:0] icmp_ln878_1_reg_268;
reg   [0:0] icmp_ln878_2_reg_273;
reg   [3:0] ping_0_address0;
reg    ping_0_ce0;
reg    ping_0_we0;
wire   [31:0] ping_0_q0;
reg   [3:0] ping_1_address0;
reg    ping_1_ce0;
reg    ping_1_we0;
wire   [31:0] ping_1_q0;
reg   [3:0] ping_2_address0;
reg    ping_2_ce0;
reg    ping_2_we0;
wire   [31:0] ping_2_q0;
reg   [3:0] ping_3_address0;
reg    ping_3_ce0;
reg    ping_3_we0;
wire   [31:0] ping_3_q0;
reg   [3:0] ping_4_address0;
reg    ping_4_ce0;
reg    ping_4_we0;
wire   [31:0] ping_4_q0;
reg   [3:0] ping_5_address0;
reg    ping_5_ce0;
reg    ping_5_we0;
wire   [31:0] ping_5_q0;
reg   [3:0] ping_6_address0;
reg    ping_6_ce0;
reg    ping_6_we0;
wire   [31:0] ping_6_q0;
reg   [3:0] ping_7_address0;
reg    ping_7_ce0;
reg    ping_7_we0;
wire   [31:0] ping_7_q0;
reg   [3:0] ping_8_address0;
reg    ping_8_ce0;
reg    ping_8_we0;
wire   [31:0] ping_8_q0;
reg   [3:0] ping_9_address0;
reg    ping_9_ce0;
reg    ping_9_we0;
wire   [31:0] ping_9_q0;
reg   [3:0] pong_0_address0;
reg    pong_0_ce0;
reg    pong_0_we0;
wire   [31:0] pong_0_q0;
reg   [3:0] pong_1_address0;
reg    pong_1_ce0;
reg    pong_1_we0;
wire   [31:0] pong_1_q0;
reg   [3:0] pong_2_address0;
reg    pong_2_ce0;
reg    pong_2_we0;
wire   [31:0] pong_2_q0;
reg   [3:0] pong_3_address0;
reg    pong_3_ce0;
reg    pong_3_we0;
wire   [31:0] pong_3_q0;
reg   [3:0] pong_4_address0;
reg    pong_4_ce0;
reg    pong_4_we0;
wire   [31:0] pong_4_q0;
reg   [3:0] pong_5_address0;
reg    pong_5_ce0;
reg    pong_5_we0;
wire   [31:0] pong_5_q0;
reg   [3:0] pong_6_address0;
reg    pong_6_ce0;
reg    pong_6_we0;
wire   [31:0] pong_6_q0;
reg   [3:0] pong_7_address0;
reg    pong_7_ce0;
reg    pong_7_we0;
wire   [31:0] pong_7_q0;
reg   [3:0] pong_8_address0;
reg    pong_8_ce0;
reg    pong_8_we0;
wire   [31:0] pong_8_q0;
reg   [3:0] pong_9_address0;
reg    pong_9_ce0;
reg    pong_9_we0;
wire   [31:0] pong_9_q0;
wire    grp_buf2stream_fu_161_ap_start;
wire    grp_buf2stream_fu_161_ap_done;
wire    grp_buf2stream_fu_161_ap_idle;
wire    grp_buf2stream_fu_161_ap_ready;
wire   [3:0] grp_buf2stream_fu_161_buffer_0_address0;
wire    grp_buf2stream_fu_161_buffer_0_ce0;
reg   [31:0] grp_buf2stream_fu_161_buffer_0_q0;
wire   [3:0] grp_buf2stream_fu_161_buffer_1_address0;
wire    grp_buf2stream_fu_161_buffer_1_ce0;
reg   [31:0] grp_buf2stream_fu_161_buffer_1_q0;
wire   [3:0] grp_buf2stream_fu_161_buffer_2_address0;
wire    grp_buf2stream_fu_161_buffer_2_ce0;
reg   [31:0] grp_buf2stream_fu_161_buffer_2_q0;
wire   [3:0] grp_buf2stream_fu_161_buffer_3_address0;
wire    grp_buf2stream_fu_161_buffer_3_ce0;
reg   [31:0] grp_buf2stream_fu_161_buffer_3_q0;
wire   [3:0] grp_buf2stream_fu_161_buffer_4_address0;
wire    grp_buf2stream_fu_161_buffer_4_ce0;
reg   [31:0] grp_buf2stream_fu_161_buffer_4_q0;
wire   [3:0] grp_buf2stream_fu_161_buffer_5_address0;
wire    grp_buf2stream_fu_161_buffer_5_ce0;
reg   [31:0] grp_buf2stream_fu_161_buffer_5_q0;
wire   [3:0] grp_buf2stream_fu_161_buffer_6_address0;
wire    grp_buf2stream_fu_161_buffer_6_ce0;
reg   [31:0] grp_buf2stream_fu_161_buffer_6_q0;
wire   [3:0] grp_buf2stream_fu_161_buffer_7_address0;
wire    grp_buf2stream_fu_161_buffer_7_ce0;
reg   [31:0] grp_buf2stream_fu_161_buffer_7_q0;
wire   [3:0] grp_buf2stream_fu_161_buffer_8_address0;
wire    grp_buf2stream_fu_161_buffer_8_ce0;
reg   [31:0] grp_buf2stream_fu_161_buffer_8_q0;
wire   [3:0] grp_buf2stream_fu_161_buffer_9_address0;
wire    grp_buf2stream_fu_161_buffer_9_ce0;
reg   [31:0] grp_buf2stream_fu_161_buffer_9_q0;
wire   [31:0] grp_buf2stream_fu_161_dst_V_din;
wire    grp_buf2stream_fu_161_dst_V_write;
wire   [31:0] grp_buf2stream_fu_161_dst_1_V_din;
wire    grp_buf2stream_fu_161_dst_1_V_write;
wire   [31:0] grp_buf2stream_fu_161_dst_2_V_din;
wire    grp_buf2stream_fu_161_dst_2_V_write;
wire   [31:0] grp_buf2stream_fu_161_dst_3_V_din;
wire    grp_buf2stream_fu_161_dst_3_V_write;
wire   [31:0] grp_buf2stream_fu_161_dst_4_V_din;
wire    grp_buf2stream_fu_161_dst_4_V_write;
reg    grp_buf2stream_fu_161_enable;
wire    grp_stream2buf_fu_186_ap_start;
wire    grp_stream2buf_fu_186_ap_done;
wire    grp_stream2buf_fu_186_ap_idle;
wire    grp_stream2buf_fu_186_ap_ready;
wire    grp_stream2buf_fu_186_src_V_read;
wire    grp_stream2buf_fu_186_src_1_V_read;
wire    grp_stream2buf_fu_186_src_2_V_read;
wire    grp_stream2buf_fu_186_src_3_V_read;
wire    grp_stream2buf_fu_186_src_4_V_read;
wire    grp_stream2buf_fu_186_src_5_V_read;
wire    grp_stream2buf_fu_186_src_6_V_read;
wire    grp_stream2buf_fu_186_src_7_V_read;
wire    grp_stream2buf_fu_186_src_8_V_read;
wire    grp_stream2buf_fu_186_src_9_V_read;
wire   [3:0] grp_stream2buf_fu_186_buffer_0_address0;
wire    grp_stream2buf_fu_186_buffer_0_ce0;
wire    grp_stream2buf_fu_186_buffer_0_we0;
wire   [31:0] grp_stream2buf_fu_186_buffer_0_d0;
wire   [3:0] grp_stream2buf_fu_186_buffer_1_address0;
wire    grp_stream2buf_fu_186_buffer_1_ce0;
wire    grp_stream2buf_fu_186_buffer_1_we0;
wire   [31:0] grp_stream2buf_fu_186_buffer_1_d0;
wire   [3:0] grp_stream2buf_fu_186_buffer_2_address0;
wire    grp_stream2buf_fu_186_buffer_2_ce0;
wire    grp_stream2buf_fu_186_buffer_2_we0;
wire   [31:0] grp_stream2buf_fu_186_buffer_2_d0;
wire   [3:0] grp_stream2buf_fu_186_buffer_3_address0;
wire    grp_stream2buf_fu_186_buffer_3_ce0;
wire    grp_stream2buf_fu_186_buffer_3_we0;
wire   [31:0] grp_stream2buf_fu_186_buffer_3_d0;
wire   [3:0] grp_stream2buf_fu_186_buffer_4_address0;
wire    grp_stream2buf_fu_186_buffer_4_ce0;
wire    grp_stream2buf_fu_186_buffer_4_we0;
wire   [31:0] grp_stream2buf_fu_186_buffer_4_d0;
wire   [3:0] grp_stream2buf_fu_186_buffer_5_address0;
wire    grp_stream2buf_fu_186_buffer_5_ce0;
wire    grp_stream2buf_fu_186_buffer_5_we0;
wire   [31:0] grp_stream2buf_fu_186_buffer_5_d0;
wire   [3:0] grp_stream2buf_fu_186_buffer_6_address0;
wire    grp_stream2buf_fu_186_buffer_6_ce0;
wire    grp_stream2buf_fu_186_buffer_6_we0;
wire   [31:0] grp_stream2buf_fu_186_buffer_6_d0;
wire   [3:0] grp_stream2buf_fu_186_buffer_7_address0;
wire    grp_stream2buf_fu_186_buffer_7_ce0;
wire    grp_stream2buf_fu_186_buffer_7_we0;
wire   [31:0] grp_stream2buf_fu_186_buffer_7_d0;
wire   [3:0] grp_stream2buf_fu_186_buffer_8_address0;
wire    grp_stream2buf_fu_186_buffer_8_ce0;
wire    grp_stream2buf_fu_186_buffer_8_we0;
wire   [31:0] grp_stream2buf_fu_186_buffer_8_d0;
wire   [3:0] grp_stream2buf_fu_186_buffer_9_address0;
wire    grp_stream2buf_fu_186_buffer_9_ce0;
wire    grp_stream2buf_fu_186_buffer_9_we0;
wire   [31:0] grp_stream2buf_fu_186_buffer_9_d0;
wire    grp_stream2buf_fu_186_enable;
reg   [4:0] p_Val2_s_reg_150;
wire    ap_CS_fsm_state3;
reg    ap_block_state3_on_subcall_done;
reg    grp_buf2stream_fu_161_ap_start_reg;
reg    grp_stream2buf_fu_186_ap_start_reg;
reg   [2:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 grp_buf2stream_fu_161_ap_start_reg = 1'b0;
#0 grp_stream2buf_fu_186_ap_start_reg = 1'b0;
end

top_ping_0 #(
    .DataWidth( 32 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
ping_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(ping_0_address0),
    .ce0(ping_0_ce0),
    .we0(ping_0_we0),
    .d0(grp_stream2buf_fu_186_buffer_0_d0),
    .q0(ping_0_q0)
);

top_ping_0 #(
    .DataWidth( 32 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
ping_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(ping_1_address0),
    .ce0(ping_1_ce0),
    .we0(ping_1_we0),
    .d0(grp_stream2buf_fu_186_buffer_1_d0),
    .q0(ping_1_q0)
);

top_ping_0 #(
    .DataWidth( 32 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
ping_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(ping_2_address0),
    .ce0(ping_2_ce0),
    .we0(ping_2_we0),
    .d0(grp_stream2buf_fu_186_buffer_2_d0),
    .q0(ping_2_q0)
);

top_ping_0 #(
    .DataWidth( 32 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
ping_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(ping_3_address0),
    .ce0(ping_3_ce0),
    .we0(ping_3_we0),
    .d0(grp_stream2buf_fu_186_buffer_3_d0),
    .q0(ping_3_q0)
);

top_ping_0 #(
    .DataWidth( 32 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
ping_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(ping_4_address0),
    .ce0(ping_4_ce0),
    .we0(ping_4_we0),
    .d0(grp_stream2buf_fu_186_buffer_4_d0),
    .q0(ping_4_q0)
);

top_ping_0 #(
    .DataWidth( 32 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
ping_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(ping_5_address0),
    .ce0(ping_5_ce0),
    .we0(ping_5_we0),
    .d0(grp_stream2buf_fu_186_buffer_5_d0),
    .q0(ping_5_q0)
);

top_ping_0 #(
    .DataWidth( 32 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
ping_6_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(ping_6_address0),
    .ce0(ping_6_ce0),
    .we0(ping_6_we0),
    .d0(grp_stream2buf_fu_186_buffer_6_d0),
    .q0(ping_6_q0)
);

top_ping_0 #(
    .DataWidth( 32 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
ping_7_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(ping_7_address0),
    .ce0(ping_7_ce0),
    .we0(ping_7_we0),
    .d0(grp_stream2buf_fu_186_buffer_7_d0),
    .q0(ping_7_q0)
);

top_ping_0 #(
    .DataWidth( 32 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
ping_8_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(ping_8_address0),
    .ce0(ping_8_ce0),
    .we0(ping_8_we0),
    .d0(grp_stream2buf_fu_186_buffer_8_d0),
    .q0(ping_8_q0)
);

top_ping_0 #(
    .DataWidth( 32 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
ping_9_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(ping_9_address0),
    .ce0(ping_9_ce0),
    .we0(ping_9_we0),
    .d0(grp_stream2buf_fu_186_buffer_9_d0),
    .q0(ping_9_q0)
);

top_ping_0 #(
    .DataWidth( 32 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
pong_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(pong_0_address0),
    .ce0(pong_0_ce0),
    .we0(pong_0_we0),
    .d0(grp_stream2buf_fu_186_buffer_0_d0),
    .q0(pong_0_q0)
);

top_ping_0 #(
    .DataWidth( 32 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
pong_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(pong_1_address0),
    .ce0(pong_1_ce0),
    .we0(pong_1_we0),
    .d0(grp_stream2buf_fu_186_buffer_1_d0),
    .q0(pong_1_q0)
);

top_ping_0 #(
    .DataWidth( 32 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
pong_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(pong_2_address0),
    .ce0(pong_2_ce0),
    .we0(pong_2_we0),
    .d0(grp_stream2buf_fu_186_buffer_2_d0),
    .q0(pong_2_q0)
);

top_ping_0 #(
    .DataWidth( 32 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
pong_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(pong_3_address0),
    .ce0(pong_3_ce0),
    .we0(pong_3_we0),
    .d0(grp_stream2buf_fu_186_buffer_3_d0),
    .q0(pong_3_q0)
);

top_ping_0 #(
    .DataWidth( 32 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
pong_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(pong_4_address0),
    .ce0(pong_4_ce0),
    .we0(pong_4_we0),
    .d0(grp_stream2buf_fu_186_buffer_4_d0),
    .q0(pong_4_q0)
);

top_ping_0 #(
    .DataWidth( 32 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
pong_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(pong_5_address0),
    .ce0(pong_5_ce0),
    .we0(pong_5_we0),
    .d0(grp_stream2buf_fu_186_buffer_5_d0),
    .q0(pong_5_q0)
);

top_ping_0 #(
    .DataWidth( 32 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
pong_6_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(pong_6_address0),
    .ce0(pong_6_ce0),
    .we0(pong_6_we0),
    .d0(grp_stream2buf_fu_186_buffer_6_d0),
    .q0(pong_6_q0)
);

top_ping_0 #(
    .DataWidth( 32 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
pong_7_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(pong_7_address0),
    .ce0(pong_7_ce0),
    .we0(pong_7_we0),
    .d0(grp_stream2buf_fu_186_buffer_7_d0),
    .q0(pong_7_q0)
);

top_ping_0 #(
    .DataWidth( 32 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
pong_8_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(pong_8_address0),
    .ce0(pong_8_ce0),
    .we0(pong_8_we0),
    .d0(grp_stream2buf_fu_186_buffer_8_d0),
    .q0(pong_8_q0)
);

top_ping_0 #(
    .DataWidth( 32 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
pong_9_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(pong_9_address0),
    .ce0(pong_9_ce0),
    .we0(pong_9_we0),
    .d0(grp_stream2buf_fu_186_buffer_9_d0),
    .q0(pong_9_q0)
);

top_buf2stream grp_buf2stream_fu_161(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_buf2stream_fu_161_ap_start),
    .ap_done(grp_buf2stream_fu_161_ap_done),
    .ap_idle(grp_buf2stream_fu_161_ap_idle),
    .ap_ready(grp_buf2stream_fu_161_ap_ready),
    .buffer_0_address0(grp_buf2stream_fu_161_buffer_0_address0),
    .buffer_0_ce0(grp_buf2stream_fu_161_buffer_0_ce0),
    .buffer_0_q0(grp_buf2stream_fu_161_buffer_0_q0),
    .buffer_1_address0(grp_buf2stream_fu_161_buffer_1_address0),
    .buffer_1_ce0(grp_buf2stream_fu_161_buffer_1_ce0),
    .buffer_1_q0(grp_buf2stream_fu_161_buffer_1_q0),
    .buffer_2_address0(grp_buf2stream_fu_161_buffer_2_address0),
    .buffer_2_ce0(grp_buf2stream_fu_161_buffer_2_ce0),
    .buffer_2_q0(grp_buf2stream_fu_161_buffer_2_q0),
    .buffer_3_address0(grp_buf2stream_fu_161_buffer_3_address0),
    .buffer_3_ce0(grp_buf2stream_fu_161_buffer_3_ce0),
    .buffer_3_q0(grp_buf2stream_fu_161_buffer_3_q0),
    .buffer_4_address0(grp_buf2stream_fu_161_buffer_4_address0),
    .buffer_4_ce0(grp_buf2stream_fu_161_buffer_4_ce0),
    .buffer_4_q0(grp_buf2stream_fu_161_buffer_4_q0),
    .buffer_5_address0(grp_buf2stream_fu_161_buffer_5_address0),
    .buffer_5_ce0(grp_buf2stream_fu_161_buffer_5_ce0),
    .buffer_5_q0(grp_buf2stream_fu_161_buffer_5_q0),
    .buffer_6_address0(grp_buf2stream_fu_161_buffer_6_address0),
    .buffer_6_ce0(grp_buf2stream_fu_161_buffer_6_ce0),
    .buffer_6_q0(grp_buf2stream_fu_161_buffer_6_q0),
    .buffer_7_address0(grp_buf2stream_fu_161_buffer_7_address0),
    .buffer_7_ce0(grp_buf2stream_fu_161_buffer_7_ce0),
    .buffer_7_q0(grp_buf2stream_fu_161_buffer_7_q0),
    .buffer_8_address0(grp_buf2stream_fu_161_buffer_8_address0),
    .buffer_8_ce0(grp_buf2stream_fu_161_buffer_8_ce0),
    .buffer_8_q0(grp_buf2stream_fu_161_buffer_8_q0),
    .buffer_9_address0(grp_buf2stream_fu_161_buffer_9_address0),
    .buffer_9_ce0(grp_buf2stream_fu_161_buffer_9_ce0),
    .buffer_9_q0(grp_buf2stream_fu_161_buffer_9_q0),
    .dst_V_din(grp_buf2stream_fu_161_dst_V_din),
    .dst_V_full_n(dst_V_0_full_n),
    .dst_V_write(grp_buf2stream_fu_161_dst_V_write),
    .dst_1_V_din(grp_buf2stream_fu_161_dst_1_V_din),
    .dst_1_V_full_n(dst_V_1_full_n),
    .dst_1_V_write(grp_buf2stream_fu_161_dst_1_V_write),
    .dst_2_V_din(grp_buf2stream_fu_161_dst_2_V_din),
    .dst_2_V_full_n(dst_V_2_full_n),
    .dst_2_V_write(grp_buf2stream_fu_161_dst_2_V_write),
    .dst_3_V_din(grp_buf2stream_fu_161_dst_3_V_din),
    .dst_3_V_full_n(dst_V_3_full_n),
    .dst_3_V_write(grp_buf2stream_fu_161_dst_3_V_write),
    .dst_4_V_din(grp_buf2stream_fu_161_dst_4_V_din),
    .dst_4_V_full_n(dst_V_4_full_n),
    .dst_4_V_write(grp_buf2stream_fu_161_dst_4_V_write),
    .enable(grp_buf2stream_fu_161_enable)
);

top_stream2buf grp_stream2buf_fu_186(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_stream2buf_fu_186_ap_start),
    .ap_done(grp_stream2buf_fu_186_ap_done),
    .ap_idle(grp_stream2buf_fu_186_ap_idle),
    .ap_ready(grp_stream2buf_fu_186_ap_ready),
    .src_V_dout(src_V_0_dout),
    .src_V_empty_n(src_V_0_empty_n),
    .src_V_read(grp_stream2buf_fu_186_src_V_read),
    .src_1_V_dout(src_V_1_dout),
    .src_1_V_empty_n(src_V_1_empty_n),
    .src_1_V_read(grp_stream2buf_fu_186_src_1_V_read),
    .src_2_V_dout(src_V_2_dout),
    .src_2_V_empty_n(src_V_2_empty_n),
    .src_2_V_read(grp_stream2buf_fu_186_src_2_V_read),
    .src_3_V_dout(src_V_3_dout),
    .src_3_V_empty_n(src_V_3_empty_n),
    .src_3_V_read(grp_stream2buf_fu_186_src_3_V_read),
    .src_4_V_dout(src_V_4_dout),
    .src_4_V_empty_n(src_V_4_empty_n),
    .src_4_V_read(grp_stream2buf_fu_186_src_4_V_read),
    .src_5_V_dout(src_V_5_dout),
    .src_5_V_empty_n(src_V_5_empty_n),
    .src_5_V_read(grp_stream2buf_fu_186_src_5_V_read),
    .src_6_V_dout(src_V_6_dout),
    .src_6_V_empty_n(src_V_6_empty_n),
    .src_6_V_read(grp_stream2buf_fu_186_src_6_V_read),
    .src_7_V_dout(src_V_7_dout),
    .src_7_V_empty_n(src_V_7_empty_n),
    .src_7_V_read(grp_stream2buf_fu_186_src_7_V_read),
    .src_8_V_dout(src_V_8_dout),
    .src_8_V_empty_n(src_V_8_empty_n),
    .src_8_V_read(grp_stream2buf_fu_186_src_8_V_read),
    .src_9_V_dout(src_V_9_dout),
    .src_9_V_empty_n(src_V_9_empty_n),
    .src_9_V_read(grp_stream2buf_fu_186_src_9_V_read),
    .buffer_0_address0(grp_stream2buf_fu_186_buffer_0_address0),
    .buffer_0_ce0(grp_stream2buf_fu_186_buffer_0_ce0),
    .buffer_0_we0(grp_stream2buf_fu_186_buffer_0_we0),
    .buffer_0_d0(grp_stream2buf_fu_186_buffer_0_d0),
    .buffer_1_address0(grp_stream2buf_fu_186_buffer_1_address0),
    .buffer_1_ce0(grp_stream2buf_fu_186_buffer_1_ce0),
    .buffer_1_we0(grp_stream2buf_fu_186_buffer_1_we0),
    .buffer_1_d0(grp_stream2buf_fu_186_buffer_1_d0),
    .buffer_2_address0(grp_stream2buf_fu_186_buffer_2_address0),
    .buffer_2_ce0(grp_stream2buf_fu_186_buffer_2_ce0),
    .buffer_2_we0(grp_stream2buf_fu_186_buffer_2_we0),
    .buffer_2_d0(grp_stream2buf_fu_186_buffer_2_d0),
    .buffer_3_address0(grp_stream2buf_fu_186_buffer_3_address0),
    .buffer_3_ce0(grp_stream2buf_fu_186_buffer_3_ce0),
    .buffer_3_we0(grp_stream2buf_fu_186_buffer_3_we0),
    .buffer_3_d0(grp_stream2buf_fu_186_buffer_3_d0),
    .buffer_4_address0(grp_stream2buf_fu_186_buffer_4_address0),
    .buffer_4_ce0(grp_stream2buf_fu_186_buffer_4_ce0),
    .buffer_4_we0(grp_stream2buf_fu_186_buffer_4_we0),
    .buffer_4_d0(grp_stream2buf_fu_186_buffer_4_d0),
    .buffer_5_address0(grp_stream2buf_fu_186_buffer_5_address0),
    .buffer_5_ce0(grp_stream2buf_fu_186_buffer_5_ce0),
    .buffer_5_we0(grp_stream2buf_fu_186_buffer_5_we0),
    .buffer_5_d0(grp_stream2buf_fu_186_buffer_5_d0),
    .buffer_6_address0(grp_stream2buf_fu_186_buffer_6_address0),
    .buffer_6_ce0(grp_stream2buf_fu_186_buffer_6_ce0),
    .buffer_6_we0(grp_stream2buf_fu_186_buffer_6_we0),
    .buffer_6_d0(grp_stream2buf_fu_186_buffer_6_d0),
    .buffer_7_address0(grp_stream2buf_fu_186_buffer_7_address0),
    .buffer_7_ce0(grp_stream2buf_fu_186_buffer_7_ce0),
    .buffer_7_we0(grp_stream2buf_fu_186_buffer_7_we0),
    .buffer_7_d0(grp_stream2buf_fu_186_buffer_7_d0),
    .buffer_8_address0(grp_stream2buf_fu_186_buffer_8_address0),
    .buffer_8_ce0(grp_stream2buf_fu_186_buffer_8_ce0),
    .buffer_8_we0(grp_stream2buf_fu_186_buffer_8_we0),
    .buffer_8_d0(grp_stream2buf_fu_186_buffer_8_d0),
    .buffer_9_address0(grp_stream2buf_fu_186_buffer_9_address0),
    .buffer_9_ce0(grp_stream2buf_fu_186_buffer_9_ce0),
    .buffer_9_we0(grp_stream2buf_fu_186_buffer_9_we0),
    .buffer_9_d0(grp_stream2buf_fu_186_buffer_9_d0),
    .enable(grp_stream2buf_fu_186_enable)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_buf2stream_fu_161_ap_start_reg <= 1'b0;
    end else begin
        if ((((icmp_ln47_fu_232_p2 == 1'd0) & (trunc_ln47_fu_228_p1 == 1'd1) & (1'b1 == ap_CS_fsm_state2)) | ((icmp_ln47_fu_232_p2 == 1'd0) & (trunc_ln47_fu_228_p1 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
            grp_buf2stream_fu_161_ap_start_reg <= 1'b1;
        end else if ((grp_buf2stream_fu_161_ap_ready == 1'b1)) begin
            grp_buf2stream_fu_161_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_stream2buf_fu_186_ap_start_reg <= 1'b0;
    end else begin
        if ((((icmp_ln47_fu_232_p2 == 1'd0) & (trunc_ln47_fu_228_p1 == 1'd1) & (1'b1 == ap_CS_fsm_state2)) | ((icmp_ln47_fu_232_p2 == 1'd0) & (trunc_ln47_fu_228_p1 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
            grp_stream2buf_fu_186_ap_start_reg <= 1'b1;
        end else if ((grp_stream2buf_fu_186_ap_ready == 1'b1)) begin
            grp_stream2buf_fu_186_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_Val2_s_reg_150 <= 5'd0;
    end else if (((1'b0 == ap_block_state3_on_subcall_done) & (1'b1 == ap_CS_fsm_state3))) begin
        p_Val2_s_reg_150 <= i_reg_258;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        i_reg_258 <= i_fu_238_p2;
        trunc_ln47_reg_251 <= trunc_ln47_fu_228_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln47_fu_232_p2 == 1'd0) & (trunc_ln47_fu_228_p1 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        icmp_ln878_1_reg_268 <= grp_fu_221_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln47_fu_232_p2 == 1'd0) & (trunc_ln47_fu_228_p1 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        icmp_ln878_2_reg_273 <= grp_fu_221_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln47_fu_232_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        icmp_ln878_reg_263 <= icmp_ln878_fu_244_p2;
    end
end

always @ (*) begin
    if (((icmp_ln47_fu_232_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln47_fu_232_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((((trunc_ln47_reg_251 == 1'd1) & (1'b1 == ap_CS_fsm_state3)) | ((trunc_ln47_reg_251 == 1'd0) & (1'b1 == ap_CS_fsm_state3)))) begin
        dst_V_0_write = grp_buf2stream_fu_161_dst_V_write;
    end else begin
        dst_V_0_write = 1'b0;
    end
end

always @ (*) begin
    if ((((trunc_ln47_reg_251 == 1'd1) & (1'b1 == ap_CS_fsm_state3)) | ((trunc_ln47_reg_251 == 1'd0) & (1'b1 == ap_CS_fsm_state3)))) begin
        dst_V_1_write = grp_buf2stream_fu_161_dst_1_V_write;
    end else begin
        dst_V_1_write = 1'b0;
    end
end

always @ (*) begin
    if ((((trunc_ln47_reg_251 == 1'd1) & (1'b1 == ap_CS_fsm_state3)) | ((trunc_ln47_reg_251 == 1'd0) & (1'b1 == ap_CS_fsm_state3)))) begin
        dst_V_2_write = grp_buf2stream_fu_161_dst_2_V_write;
    end else begin
        dst_V_2_write = 1'b0;
    end
end

always @ (*) begin
    if ((((trunc_ln47_reg_251 == 1'd1) & (1'b1 == ap_CS_fsm_state3)) | ((trunc_ln47_reg_251 == 1'd0) & (1'b1 == ap_CS_fsm_state3)))) begin
        dst_V_3_write = grp_buf2stream_fu_161_dst_3_V_write;
    end else begin
        dst_V_3_write = 1'b0;
    end
end

always @ (*) begin
    if ((((trunc_ln47_reg_251 == 1'd1) & (1'b1 == ap_CS_fsm_state3)) | ((trunc_ln47_reg_251 == 1'd0) & (1'b1 == ap_CS_fsm_state3)))) begin
        dst_V_4_write = grp_buf2stream_fu_161_dst_4_V_write;
    end else begin
        dst_V_4_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((trunc_ln47_reg_251 == 1'd1)) begin
            grp_buf2stream_fu_161_buffer_0_q0 = pong_0_q0;
        end else if ((trunc_ln47_reg_251 == 1'd0)) begin
            grp_buf2stream_fu_161_buffer_0_q0 = ping_0_q0;
        end else begin
            grp_buf2stream_fu_161_buffer_0_q0 = 'bx;
        end
    end else begin
        grp_buf2stream_fu_161_buffer_0_q0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((trunc_ln47_reg_251 == 1'd1)) begin
            grp_buf2stream_fu_161_buffer_1_q0 = pong_1_q0;
        end else if ((trunc_ln47_reg_251 == 1'd0)) begin
            grp_buf2stream_fu_161_buffer_1_q0 = ping_1_q0;
        end else begin
            grp_buf2stream_fu_161_buffer_1_q0 = 'bx;
        end
    end else begin
        grp_buf2stream_fu_161_buffer_1_q0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((trunc_ln47_reg_251 == 1'd1)) begin
            grp_buf2stream_fu_161_buffer_2_q0 = pong_2_q0;
        end else if ((trunc_ln47_reg_251 == 1'd0)) begin
            grp_buf2stream_fu_161_buffer_2_q0 = ping_2_q0;
        end else begin
            grp_buf2stream_fu_161_buffer_2_q0 = 'bx;
        end
    end else begin
        grp_buf2stream_fu_161_buffer_2_q0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((trunc_ln47_reg_251 == 1'd1)) begin
            grp_buf2stream_fu_161_buffer_3_q0 = pong_3_q0;
        end else if ((trunc_ln47_reg_251 == 1'd0)) begin
            grp_buf2stream_fu_161_buffer_3_q0 = ping_3_q0;
        end else begin
            grp_buf2stream_fu_161_buffer_3_q0 = 'bx;
        end
    end else begin
        grp_buf2stream_fu_161_buffer_3_q0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((trunc_ln47_reg_251 == 1'd1)) begin
            grp_buf2stream_fu_161_buffer_4_q0 = pong_4_q0;
        end else if ((trunc_ln47_reg_251 == 1'd0)) begin
            grp_buf2stream_fu_161_buffer_4_q0 = ping_4_q0;
        end else begin
            grp_buf2stream_fu_161_buffer_4_q0 = 'bx;
        end
    end else begin
        grp_buf2stream_fu_161_buffer_4_q0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((trunc_ln47_reg_251 == 1'd1)) begin
            grp_buf2stream_fu_161_buffer_5_q0 = pong_5_q0;
        end else if ((trunc_ln47_reg_251 == 1'd0)) begin
            grp_buf2stream_fu_161_buffer_5_q0 = ping_5_q0;
        end else begin
            grp_buf2stream_fu_161_buffer_5_q0 = 'bx;
        end
    end else begin
        grp_buf2stream_fu_161_buffer_5_q0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((trunc_ln47_reg_251 == 1'd1)) begin
            grp_buf2stream_fu_161_buffer_6_q0 = pong_6_q0;
        end else if ((trunc_ln47_reg_251 == 1'd0)) begin
            grp_buf2stream_fu_161_buffer_6_q0 = ping_6_q0;
        end else begin
            grp_buf2stream_fu_161_buffer_6_q0 = 'bx;
        end
    end else begin
        grp_buf2stream_fu_161_buffer_6_q0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((trunc_ln47_reg_251 == 1'd1)) begin
            grp_buf2stream_fu_161_buffer_7_q0 = pong_7_q0;
        end else if ((trunc_ln47_reg_251 == 1'd0)) begin
            grp_buf2stream_fu_161_buffer_7_q0 = ping_7_q0;
        end else begin
            grp_buf2stream_fu_161_buffer_7_q0 = 'bx;
        end
    end else begin
        grp_buf2stream_fu_161_buffer_7_q0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((trunc_ln47_reg_251 == 1'd1)) begin
            grp_buf2stream_fu_161_buffer_8_q0 = pong_8_q0;
        end else if ((trunc_ln47_reg_251 == 1'd0)) begin
            grp_buf2stream_fu_161_buffer_8_q0 = ping_8_q0;
        end else begin
            grp_buf2stream_fu_161_buffer_8_q0 = 'bx;
        end
    end else begin
        grp_buf2stream_fu_161_buffer_8_q0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((trunc_ln47_reg_251 == 1'd1)) begin
            grp_buf2stream_fu_161_buffer_9_q0 = pong_9_q0;
        end else if ((trunc_ln47_reg_251 == 1'd0)) begin
            grp_buf2stream_fu_161_buffer_9_q0 = ping_9_q0;
        end else begin
            grp_buf2stream_fu_161_buffer_9_q0 = 'bx;
        end
    end else begin
        grp_buf2stream_fu_161_buffer_9_q0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((trunc_ln47_reg_251 == 1'd1)) begin
            grp_buf2stream_fu_161_enable = icmp_ln878_2_reg_273;
        end else if ((trunc_ln47_reg_251 == 1'd0)) begin
            grp_buf2stream_fu_161_enable = icmp_ln878_1_reg_268;
        end else begin
            grp_buf2stream_fu_161_enable = 'bx;
        end
    end else begin
        grp_buf2stream_fu_161_enable = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((trunc_ln47_reg_251 == 1'd1)) begin
            ping_0_address0 = grp_stream2buf_fu_186_buffer_0_address0;
        end else if ((trunc_ln47_reg_251 == 1'd0)) begin
            ping_0_address0 = grp_buf2stream_fu_161_buffer_0_address0;
        end else begin
            ping_0_address0 = 'bx;
        end
    end else begin
        ping_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((trunc_ln47_reg_251 == 1'd1)) begin
            ping_0_ce0 = grp_stream2buf_fu_186_buffer_0_ce0;
        end else if ((trunc_ln47_reg_251 == 1'd0)) begin
            ping_0_ce0 = grp_buf2stream_fu_161_buffer_0_ce0;
        end else begin
            ping_0_ce0 = 1'b0;
        end
    end else begin
        ping_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln47_reg_251 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        ping_0_we0 = grp_stream2buf_fu_186_buffer_0_we0;
    end else begin
        ping_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((trunc_ln47_reg_251 == 1'd1)) begin
            ping_1_address0 = grp_stream2buf_fu_186_buffer_1_address0;
        end else if ((trunc_ln47_reg_251 == 1'd0)) begin
            ping_1_address0 = grp_buf2stream_fu_161_buffer_1_address0;
        end else begin
            ping_1_address0 = 'bx;
        end
    end else begin
        ping_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((trunc_ln47_reg_251 == 1'd1)) begin
            ping_1_ce0 = grp_stream2buf_fu_186_buffer_1_ce0;
        end else if ((trunc_ln47_reg_251 == 1'd0)) begin
            ping_1_ce0 = grp_buf2stream_fu_161_buffer_1_ce0;
        end else begin
            ping_1_ce0 = 1'b0;
        end
    end else begin
        ping_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln47_reg_251 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        ping_1_we0 = grp_stream2buf_fu_186_buffer_1_we0;
    end else begin
        ping_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((trunc_ln47_reg_251 == 1'd1)) begin
            ping_2_address0 = grp_stream2buf_fu_186_buffer_2_address0;
        end else if ((trunc_ln47_reg_251 == 1'd0)) begin
            ping_2_address0 = grp_buf2stream_fu_161_buffer_2_address0;
        end else begin
            ping_2_address0 = 'bx;
        end
    end else begin
        ping_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((trunc_ln47_reg_251 == 1'd1)) begin
            ping_2_ce0 = grp_stream2buf_fu_186_buffer_2_ce0;
        end else if ((trunc_ln47_reg_251 == 1'd0)) begin
            ping_2_ce0 = grp_buf2stream_fu_161_buffer_2_ce0;
        end else begin
            ping_2_ce0 = 1'b0;
        end
    end else begin
        ping_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln47_reg_251 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        ping_2_we0 = grp_stream2buf_fu_186_buffer_2_we0;
    end else begin
        ping_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((trunc_ln47_reg_251 == 1'd1)) begin
            ping_3_address0 = grp_stream2buf_fu_186_buffer_3_address0;
        end else if ((trunc_ln47_reg_251 == 1'd0)) begin
            ping_3_address0 = grp_buf2stream_fu_161_buffer_3_address0;
        end else begin
            ping_3_address0 = 'bx;
        end
    end else begin
        ping_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((trunc_ln47_reg_251 == 1'd1)) begin
            ping_3_ce0 = grp_stream2buf_fu_186_buffer_3_ce0;
        end else if ((trunc_ln47_reg_251 == 1'd0)) begin
            ping_3_ce0 = grp_buf2stream_fu_161_buffer_3_ce0;
        end else begin
            ping_3_ce0 = 1'b0;
        end
    end else begin
        ping_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln47_reg_251 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        ping_3_we0 = grp_stream2buf_fu_186_buffer_3_we0;
    end else begin
        ping_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((trunc_ln47_reg_251 == 1'd1)) begin
            ping_4_address0 = grp_stream2buf_fu_186_buffer_4_address0;
        end else if ((trunc_ln47_reg_251 == 1'd0)) begin
            ping_4_address0 = grp_buf2stream_fu_161_buffer_4_address0;
        end else begin
            ping_4_address0 = 'bx;
        end
    end else begin
        ping_4_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((trunc_ln47_reg_251 == 1'd1)) begin
            ping_4_ce0 = grp_stream2buf_fu_186_buffer_4_ce0;
        end else if ((trunc_ln47_reg_251 == 1'd0)) begin
            ping_4_ce0 = grp_buf2stream_fu_161_buffer_4_ce0;
        end else begin
            ping_4_ce0 = 1'b0;
        end
    end else begin
        ping_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln47_reg_251 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        ping_4_we0 = grp_stream2buf_fu_186_buffer_4_we0;
    end else begin
        ping_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((trunc_ln47_reg_251 == 1'd1)) begin
            ping_5_address0 = grp_stream2buf_fu_186_buffer_5_address0;
        end else if ((trunc_ln47_reg_251 == 1'd0)) begin
            ping_5_address0 = grp_buf2stream_fu_161_buffer_5_address0;
        end else begin
            ping_5_address0 = 'bx;
        end
    end else begin
        ping_5_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((trunc_ln47_reg_251 == 1'd1)) begin
            ping_5_ce0 = grp_stream2buf_fu_186_buffer_5_ce0;
        end else if ((trunc_ln47_reg_251 == 1'd0)) begin
            ping_5_ce0 = grp_buf2stream_fu_161_buffer_5_ce0;
        end else begin
            ping_5_ce0 = 1'b0;
        end
    end else begin
        ping_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln47_reg_251 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        ping_5_we0 = grp_stream2buf_fu_186_buffer_5_we0;
    end else begin
        ping_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((trunc_ln47_reg_251 == 1'd1)) begin
            ping_6_address0 = grp_stream2buf_fu_186_buffer_6_address0;
        end else if ((trunc_ln47_reg_251 == 1'd0)) begin
            ping_6_address0 = grp_buf2stream_fu_161_buffer_6_address0;
        end else begin
            ping_6_address0 = 'bx;
        end
    end else begin
        ping_6_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((trunc_ln47_reg_251 == 1'd1)) begin
            ping_6_ce0 = grp_stream2buf_fu_186_buffer_6_ce0;
        end else if ((trunc_ln47_reg_251 == 1'd0)) begin
            ping_6_ce0 = grp_buf2stream_fu_161_buffer_6_ce0;
        end else begin
            ping_6_ce0 = 1'b0;
        end
    end else begin
        ping_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln47_reg_251 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        ping_6_we0 = grp_stream2buf_fu_186_buffer_6_we0;
    end else begin
        ping_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((trunc_ln47_reg_251 == 1'd1)) begin
            ping_7_address0 = grp_stream2buf_fu_186_buffer_7_address0;
        end else if ((trunc_ln47_reg_251 == 1'd0)) begin
            ping_7_address0 = grp_buf2stream_fu_161_buffer_7_address0;
        end else begin
            ping_7_address0 = 'bx;
        end
    end else begin
        ping_7_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((trunc_ln47_reg_251 == 1'd1)) begin
            ping_7_ce0 = grp_stream2buf_fu_186_buffer_7_ce0;
        end else if ((trunc_ln47_reg_251 == 1'd0)) begin
            ping_7_ce0 = grp_buf2stream_fu_161_buffer_7_ce0;
        end else begin
            ping_7_ce0 = 1'b0;
        end
    end else begin
        ping_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln47_reg_251 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        ping_7_we0 = grp_stream2buf_fu_186_buffer_7_we0;
    end else begin
        ping_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((trunc_ln47_reg_251 == 1'd1)) begin
            ping_8_address0 = grp_stream2buf_fu_186_buffer_8_address0;
        end else if ((trunc_ln47_reg_251 == 1'd0)) begin
            ping_8_address0 = grp_buf2stream_fu_161_buffer_8_address0;
        end else begin
            ping_8_address0 = 'bx;
        end
    end else begin
        ping_8_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((trunc_ln47_reg_251 == 1'd1)) begin
            ping_8_ce0 = grp_stream2buf_fu_186_buffer_8_ce0;
        end else if ((trunc_ln47_reg_251 == 1'd0)) begin
            ping_8_ce0 = grp_buf2stream_fu_161_buffer_8_ce0;
        end else begin
            ping_8_ce0 = 1'b0;
        end
    end else begin
        ping_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln47_reg_251 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        ping_8_we0 = grp_stream2buf_fu_186_buffer_8_we0;
    end else begin
        ping_8_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((trunc_ln47_reg_251 == 1'd1)) begin
            ping_9_address0 = grp_stream2buf_fu_186_buffer_9_address0;
        end else if ((trunc_ln47_reg_251 == 1'd0)) begin
            ping_9_address0 = grp_buf2stream_fu_161_buffer_9_address0;
        end else begin
            ping_9_address0 = 'bx;
        end
    end else begin
        ping_9_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((trunc_ln47_reg_251 == 1'd1)) begin
            ping_9_ce0 = grp_stream2buf_fu_186_buffer_9_ce0;
        end else if ((trunc_ln47_reg_251 == 1'd0)) begin
            ping_9_ce0 = grp_buf2stream_fu_161_buffer_9_ce0;
        end else begin
            ping_9_ce0 = 1'b0;
        end
    end else begin
        ping_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln47_reg_251 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        ping_9_we0 = grp_stream2buf_fu_186_buffer_9_we0;
    end else begin
        ping_9_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((trunc_ln47_reg_251 == 1'd0)) begin
            pong_0_address0 = grp_stream2buf_fu_186_buffer_0_address0;
        end else if ((trunc_ln47_reg_251 == 1'd1)) begin
            pong_0_address0 = grp_buf2stream_fu_161_buffer_0_address0;
        end else begin
            pong_0_address0 = 'bx;
        end
    end else begin
        pong_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((trunc_ln47_reg_251 == 1'd0)) begin
            pong_0_ce0 = grp_stream2buf_fu_186_buffer_0_ce0;
        end else if ((trunc_ln47_reg_251 == 1'd1)) begin
            pong_0_ce0 = grp_buf2stream_fu_161_buffer_0_ce0;
        end else begin
            pong_0_ce0 = 1'b0;
        end
    end else begin
        pong_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln47_reg_251 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        pong_0_we0 = grp_stream2buf_fu_186_buffer_0_we0;
    end else begin
        pong_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((trunc_ln47_reg_251 == 1'd0)) begin
            pong_1_address0 = grp_stream2buf_fu_186_buffer_1_address0;
        end else if ((trunc_ln47_reg_251 == 1'd1)) begin
            pong_1_address0 = grp_buf2stream_fu_161_buffer_1_address0;
        end else begin
            pong_1_address0 = 'bx;
        end
    end else begin
        pong_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((trunc_ln47_reg_251 == 1'd0)) begin
            pong_1_ce0 = grp_stream2buf_fu_186_buffer_1_ce0;
        end else if ((trunc_ln47_reg_251 == 1'd1)) begin
            pong_1_ce0 = grp_buf2stream_fu_161_buffer_1_ce0;
        end else begin
            pong_1_ce0 = 1'b0;
        end
    end else begin
        pong_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln47_reg_251 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        pong_1_we0 = grp_stream2buf_fu_186_buffer_1_we0;
    end else begin
        pong_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((trunc_ln47_reg_251 == 1'd0)) begin
            pong_2_address0 = grp_stream2buf_fu_186_buffer_2_address0;
        end else if ((trunc_ln47_reg_251 == 1'd1)) begin
            pong_2_address0 = grp_buf2stream_fu_161_buffer_2_address0;
        end else begin
            pong_2_address0 = 'bx;
        end
    end else begin
        pong_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((trunc_ln47_reg_251 == 1'd0)) begin
            pong_2_ce0 = grp_stream2buf_fu_186_buffer_2_ce0;
        end else if ((trunc_ln47_reg_251 == 1'd1)) begin
            pong_2_ce0 = grp_buf2stream_fu_161_buffer_2_ce0;
        end else begin
            pong_2_ce0 = 1'b0;
        end
    end else begin
        pong_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln47_reg_251 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        pong_2_we0 = grp_stream2buf_fu_186_buffer_2_we0;
    end else begin
        pong_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((trunc_ln47_reg_251 == 1'd0)) begin
            pong_3_address0 = grp_stream2buf_fu_186_buffer_3_address0;
        end else if ((trunc_ln47_reg_251 == 1'd1)) begin
            pong_3_address0 = grp_buf2stream_fu_161_buffer_3_address0;
        end else begin
            pong_3_address0 = 'bx;
        end
    end else begin
        pong_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((trunc_ln47_reg_251 == 1'd0)) begin
            pong_3_ce0 = grp_stream2buf_fu_186_buffer_3_ce0;
        end else if ((trunc_ln47_reg_251 == 1'd1)) begin
            pong_3_ce0 = grp_buf2stream_fu_161_buffer_3_ce0;
        end else begin
            pong_3_ce0 = 1'b0;
        end
    end else begin
        pong_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln47_reg_251 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        pong_3_we0 = grp_stream2buf_fu_186_buffer_3_we0;
    end else begin
        pong_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((trunc_ln47_reg_251 == 1'd0)) begin
            pong_4_address0 = grp_stream2buf_fu_186_buffer_4_address0;
        end else if ((trunc_ln47_reg_251 == 1'd1)) begin
            pong_4_address0 = grp_buf2stream_fu_161_buffer_4_address0;
        end else begin
            pong_4_address0 = 'bx;
        end
    end else begin
        pong_4_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((trunc_ln47_reg_251 == 1'd0)) begin
            pong_4_ce0 = grp_stream2buf_fu_186_buffer_4_ce0;
        end else if ((trunc_ln47_reg_251 == 1'd1)) begin
            pong_4_ce0 = grp_buf2stream_fu_161_buffer_4_ce0;
        end else begin
            pong_4_ce0 = 1'b0;
        end
    end else begin
        pong_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln47_reg_251 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        pong_4_we0 = grp_stream2buf_fu_186_buffer_4_we0;
    end else begin
        pong_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((trunc_ln47_reg_251 == 1'd0)) begin
            pong_5_address0 = grp_stream2buf_fu_186_buffer_5_address0;
        end else if ((trunc_ln47_reg_251 == 1'd1)) begin
            pong_5_address0 = grp_buf2stream_fu_161_buffer_5_address0;
        end else begin
            pong_5_address0 = 'bx;
        end
    end else begin
        pong_5_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((trunc_ln47_reg_251 == 1'd0)) begin
            pong_5_ce0 = grp_stream2buf_fu_186_buffer_5_ce0;
        end else if ((trunc_ln47_reg_251 == 1'd1)) begin
            pong_5_ce0 = grp_buf2stream_fu_161_buffer_5_ce0;
        end else begin
            pong_5_ce0 = 1'b0;
        end
    end else begin
        pong_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln47_reg_251 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        pong_5_we0 = grp_stream2buf_fu_186_buffer_5_we0;
    end else begin
        pong_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((trunc_ln47_reg_251 == 1'd0)) begin
            pong_6_address0 = grp_stream2buf_fu_186_buffer_6_address0;
        end else if ((trunc_ln47_reg_251 == 1'd1)) begin
            pong_6_address0 = grp_buf2stream_fu_161_buffer_6_address0;
        end else begin
            pong_6_address0 = 'bx;
        end
    end else begin
        pong_6_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((trunc_ln47_reg_251 == 1'd0)) begin
            pong_6_ce0 = grp_stream2buf_fu_186_buffer_6_ce0;
        end else if ((trunc_ln47_reg_251 == 1'd1)) begin
            pong_6_ce0 = grp_buf2stream_fu_161_buffer_6_ce0;
        end else begin
            pong_6_ce0 = 1'b0;
        end
    end else begin
        pong_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln47_reg_251 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        pong_6_we0 = grp_stream2buf_fu_186_buffer_6_we0;
    end else begin
        pong_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((trunc_ln47_reg_251 == 1'd0)) begin
            pong_7_address0 = grp_stream2buf_fu_186_buffer_7_address0;
        end else if ((trunc_ln47_reg_251 == 1'd1)) begin
            pong_7_address0 = grp_buf2stream_fu_161_buffer_7_address0;
        end else begin
            pong_7_address0 = 'bx;
        end
    end else begin
        pong_7_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((trunc_ln47_reg_251 == 1'd0)) begin
            pong_7_ce0 = grp_stream2buf_fu_186_buffer_7_ce0;
        end else if ((trunc_ln47_reg_251 == 1'd1)) begin
            pong_7_ce0 = grp_buf2stream_fu_161_buffer_7_ce0;
        end else begin
            pong_7_ce0 = 1'b0;
        end
    end else begin
        pong_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln47_reg_251 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        pong_7_we0 = grp_stream2buf_fu_186_buffer_7_we0;
    end else begin
        pong_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((trunc_ln47_reg_251 == 1'd0)) begin
            pong_8_address0 = grp_stream2buf_fu_186_buffer_8_address0;
        end else if ((trunc_ln47_reg_251 == 1'd1)) begin
            pong_8_address0 = grp_buf2stream_fu_161_buffer_8_address0;
        end else begin
            pong_8_address0 = 'bx;
        end
    end else begin
        pong_8_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((trunc_ln47_reg_251 == 1'd0)) begin
            pong_8_ce0 = grp_stream2buf_fu_186_buffer_8_ce0;
        end else if ((trunc_ln47_reg_251 == 1'd1)) begin
            pong_8_ce0 = grp_buf2stream_fu_161_buffer_8_ce0;
        end else begin
            pong_8_ce0 = 1'b0;
        end
    end else begin
        pong_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln47_reg_251 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        pong_8_we0 = grp_stream2buf_fu_186_buffer_8_we0;
    end else begin
        pong_8_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((trunc_ln47_reg_251 == 1'd0)) begin
            pong_9_address0 = grp_stream2buf_fu_186_buffer_9_address0;
        end else if ((trunc_ln47_reg_251 == 1'd1)) begin
            pong_9_address0 = grp_buf2stream_fu_161_buffer_9_address0;
        end else begin
            pong_9_address0 = 'bx;
        end
    end else begin
        pong_9_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((trunc_ln47_reg_251 == 1'd0)) begin
            pong_9_ce0 = grp_stream2buf_fu_186_buffer_9_ce0;
        end else if ((trunc_ln47_reg_251 == 1'd1)) begin
            pong_9_ce0 = grp_buf2stream_fu_161_buffer_9_ce0;
        end else begin
            pong_9_ce0 = 1'b0;
        end
    end else begin
        pong_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln47_reg_251 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        pong_9_we0 = grp_stream2buf_fu_186_buffer_9_we0;
    end else begin
        pong_9_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((trunc_ln47_reg_251 == 1'd1) & (1'b1 == ap_CS_fsm_state3)) | ((trunc_ln47_reg_251 == 1'd0) & (1'b1 == ap_CS_fsm_state3)))) begin
        src_V_0_read = grp_stream2buf_fu_186_src_V_read;
    end else begin
        src_V_0_read = 1'b0;
    end
end

always @ (*) begin
    if ((((trunc_ln47_reg_251 == 1'd1) & (1'b1 == ap_CS_fsm_state3)) | ((trunc_ln47_reg_251 == 1'd0) & (1'b1 == ap_CS_fsm_state3)))) begin
        src_V_1_read = grp_stream2buf_fu_186_src_1_V_read;
    end else begin
        src_V_1_read = 1'b0;
    end
end

always @ (*) begin
    if ((((trunc_ln47_reg_251 == 1'd1) & (1'b1 == ap_CS_fsm_state3)) | ((trunc_ln47_reg_251 == 1'd0) & (1'b1 == ap_CS_fsm_state3)))) begin
        src_V_2_read = grp_stream2buf_fu_186_src_2_V_read;
    end else begin
        src_V_2_read = 1'b0;
    end
end

always @ (*) begin
    if ((((trunc_ln47_reg_251 == 1'd1) & (1'b1 == ap_CS_fsm_state3)) | ((trunc_ln47_reg_251 == 1'd0) & (1'b1 == ap_CS_fsm_state3)))) begin
        src_V_3_read = grp_stream2buf_fu_186_src_3_V_read;
    end else begin
        src_V_3_read = 1'b0;
    end
end

always @ (*) begin
    if ((((trunc_ln47_reg_251 == 1'd1) & (1'b1 == ap_CS_fsm_state3)) | ((trunc_ln47_reg_251 == 1'd0) & (1'b1 == ap_CS_fsm_state3)))) begin
        src_V_4_read = grp_stream2buf_fu_186_src_4_V_read;
    end else begin
        src_V_4_read = 1'b0;
    end
end

always @ (*) begin
    if ((((trunc_ln47_reg_251 == 1'd1) & (1'b1 == ap_CS_fsm_state3)) | ((trunc_ln47_reg_251 == 1'd0) & (1'b1 == ap_CS_fsm_state3)))) begin
        src_V_5_read = grp_stream2buf_fu_186_src_5_V_read;
    end else begin
        src_V_5_read = 1'b0;
    end
end

always @ (*) begin
    if ((((trunc_ln47_reg_251 == 1'd1) & (1'b1 == ap_CS_fsm_state3)) | ((trunc_ln47_reg_251 == 1'd0) & (1'b1 == ap_CS_fsm_state3)))) begin
        src_V_6_read = grp_stream2buf_fu_186_src_6_V_read;
    end else begin
        src_V_6_read = 1'b0;
    end
end

always @ (*) begin
    if ((((trunc_ln47_reg_251 == 1'd1) & (1'b1 == ap_CS_fsm_state3)) | ((trunc_ln47_reg_251 == 1'd0) & (1'b1 == ap_CS_fsm_state3)))) begin
        src_V_7_read = grp_stream2buf_fu_186_src_7_V_read;
    end else begin
        src_V_7_read = 1'b0;
    end
end

always @ (*) begin
    if ((((trunc_ln47_reg_251 == 1'd1) & (1'b1 == ap_CS_fsm_state3)) | ((trunc_ln47_reg_251 == 1'd0) & (1'b1 == ap_CS_fsm_state3)))) begin
        src_V_8_read = grp_stream2buf_fu_186_src_8_V_read;
    end else begin
        src_V_8_read = 1'b0;
    end
end

always @ (*) begin
    if ((((trunc_ln47_reg_251 == 1'd1) & (1'b1 == ap_CS_fsm_state3)) | ((trunc_ln47_reg_251 == 1'd0) & (1'b1 == ap_CS_fsm_state3)))) begin
        src_V_9_read = grp_stream2buf_fu_186_src_9_V_read;
    end else begin
        src_V_9_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln47_fu_232_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b0 == ap_block_state3_on_subcall_done) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state3_on_subcall_done = (((trunc_ln47_reg_251 == 1'd1) & (grp_buf2stream_fu_161_ap_done == 1'b0)) | ((trunc_ln47_reg_251 == 1'd1) & (grp_stream2buf_fu_186_ap_done == 1'b0)) | ((trunc_ln47_reg_251 == 1'd0) & (grp_buf2stream_fu_161_ap_done == 1'b0)) | ((trunc_ln47_reg_251 == 1'd0) & (grp_stream2buf_fu_186_ap_done == 1'b0)));
end

assign dst_V_0_din = grp_buf2stream_fu_161_dst_V_din;

assign dst_V_1_din = grp_buf2stream_fu_161_dst_1_V_din;

assign dst_V_2_din = grp_buf2stream_fu_161_dst_2_V_din;

assign dst_V_3_din = grp_buf2stream_fu_161_dst_3_V_din;

assign dst_V_4_din = grp_buf2stream_fu_161_dst_4_V_din;

assign grp_buf2stream_fu_161_ap_start = grp_buf2stream_fu_161_ap_start_reg;

assign grp_fu_221_p2 = ((p_Val2_s_reg_150 != 5'd0) ? 1'b1 : 1'b0);

assign grp_stream2buf_fu_186_ap_start = grp_stream2buf_fu_186_ap_start_reg;

assign grp_stream2buf_fu_186_enable = icmp_ln878_reg_263;

assign i_fu_238_p2 = (5'd1 + p_Val2_s_reg_150);

assign icmp_ln47_fu_232_p2 = ((p_Val2_s_reg_150 == 5'd16) ? 1'b1 : 1'b0);

assign icmp_ln878_fu_244_p2 = ((p_Val2_s_reg_150 != 5'd15) ? 1'b1 : 1'b0);

assign trunc_ln47_fu_228_p1 = p_Val2_s_reg_150[0:0];

endmodule //top
